"""Shared plumbing for `tools/docgen`.

Nothing here knows what a page says. It holds the four things every generator
in this directory needs and that must be identical across them: where the repo
is, what a DO-NOT-EDIT banner looks like, how a table cell is escaped, and the
link check that runs over every page before it is written.

The link check is the reason this file exists at all. A generated reference is
worth having because it cannot lie about the interface it describes; a
generated reference full of `../../spec/hooks.yaml` links that resolve to
nothing is a different kind of lie, and one that no amount of deriving the
*content* from source prevents. So `check_links` resolves every relative
Markdown target against the page's own directory and refuses to write a page
that points at a file which is not there.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

#: Everything docgen writes lives here. `docs/en/` outside this directory is
#: hand-written and belongs to whoever writes prose.
REFERENCE_DIR = REPO_ROOT / "docs" / "en" / "reference"

GEN_CMD = "python3 tools/docgen/gen.py"


class DocgenError(Exception):
    """A generator could not derive what it was asked to derive.

    Always raised, never swallowed: the failure mode this whole directory
    exists to prevent is a page that quietly renders an empty table because an
    anchor in the source moved. An empty section is indistinguishable from a
    feature that was removed, so a generator that finds nothing where it knows
    something must be says so and exits non-zero.
    """


def banner(module: str, sources: list[str], extra: list[str] | None = None) -> str:
    """The DO NOT EDIT header, naming the generator and everything it read."""
    lines = [
        f"<!-- GENERATED by tools/docgen/{module} — DO NOT EDIT.",
        "",
        "     Derived from:",
    ]
    lines += [f"       - {s}" for s in sources]
    if extra:
        lines += ["", *[f"     {line}" for line in extra]]
    lines += [
        "",
        f"     Change the source, then run `{GEN_CMD}`. CI runs",
        f"     `{GEN_CMD} --check` and fails when this file and a fresh",
        "     run differ. -->",
    ]
    return "\n".join(lines) + "\n"


def cell(text: str) -> str:
    """One Markdown table cell: no newlines, no unescaped pipes."""
    text = " ".join(str(text).split())
    return text.replace("|", "\\|")


def code(text: str) -> str:
    """A cell rendered as inline code, or an em dash when there is nothing."""
    text = " ".join(str(text).split())
    return f"`{text}`" if text else "—"


def paragraphs(text: str) -> str:
    """Collapse hard-wrapped source prose into Markdown paragraphs."""
    out = []
    for block in re.split(r"\n\s*\n", text.strip()):
        out.append(" ".join(block.split()))
    return "\n\n".join(out)


LINK_RE = re.compile(r"\]\(([^)\s]+)\)")


def check_links(path: Path, text: str) -> None:
    """Every relative link target in `text` must exist on disk.

    Skips anything with a scheme (`https:`, `mailto:`) and pure fragments.
    A link with a `#fragment` is checked on its path half only — asserting the
    anchor too would mean parsing every target's headings, and the failure this
    catches (a page moved, or a generator that rebased a link by depth and got
    the depth wrong) is a broken path, not a broken anchor.
    """
    missing = []
    for target in LINK_RE.findall(text):
        if target.startswith("#") or "://" in target or target.startswith("mailto:"):
            continue
        rel = target.split("#", 1)[0]
        if not rel:
            continue
        if not (path.parent / rel).resolve().exists():
            missing.append(target)
    if missing:
        raise DocgenError(
            f"{path.relative_to(REPO_ROOT)} links to {len(missing)} path(s) that do not "
            f"exist: {', '.join(sorted(set(missing)))}"
        )


def read(rel: str) -> str:
    """Read a repo file by repo-relative path, with a useful error."""
    path = REPO_ROOT / rel
    if not path.exists():
        raise DocgenError(f"{rel} does not exist — docgen reads it as a source of truth.")
    return path.read_text(encoding="utf-8")


def run(cmd: list[str], *, cwd: Path | None = None) -> str:
    """Run a command and return its stdout, or raise with its stderr."""
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(cwd or REPO_ROOT),
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as exc:
        raise DocgenError(f"could not run {' '.join(cmd)}: {exc}") from exc
    if proc.returncode != 0:
        raise DocgenError(
            f"{' '.join(cmd)} exited {proc.returncode}:\n{proc.stderr.strip()}"
        )
    return proc.stdout
