# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from astra_plugin_sdk.proto import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginHostServiceStub(object):
    """============ Plugin Host Service (daemon exposes, plugins call into) ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/astra.PluginHostService/Register',
                request_serializer=plugin__pb2.PluginRegisterRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginRegisterResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/astra.PluginHostService/SubscribeEvents',
                request_serializer=plugin__pb2.PluginEventFilter.SerializeToString,
                response_deserializer=plugin__pb2.PluginEventMsg.FromString,
                _registered_method=True)
        self.SendChatMessage = channel.unary_stream(
                '/astra.PluginHostService/SendChatMessage',
                request_serializer=plugin__pb2.PluginChatRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginChatChunk.FromString,
                _registered_method=True)
        self.FireTrigger = channel.unary_unary(
                '/astra.PluginHostService/FireTrigger',
                request_serializer=plugin__pb2.PluginFireTriggerRequest.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                _registered_method=True)
        self.GetPluginSelfConfig = channel.unary_unary(
                '/astra.PluginHostService/GetPluginSelfConfig',
                request_serializer=plugin__pb2.PluginSelfIdRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginSelfConfigResponse.FromString,
                _registered_method=True)
        self.PluginLog = channel.unary_unary(
                '/astra.PluginHostService/PluginLog',
                request_serializer=plugin__pb2.PluginLogRequest.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                _registered_method=True)
        self.GetDaemonInfo = channel.unary_unary(
                '/astra.PluginHostService/GetDaemonInfo',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.PluginDaemonInfoResponse.FromString,
                _registered_method=True)


class PluginHostServiceServicer(object):
    """============ Plugin Host Service (daemon exposes, plugins call into) ============

    """

    def Register(self, request, context):
        """Plugin registration handshake
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Subscribe to daemon events (filtered)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChatMessage(self, request, context):
        """Send a chat message (for client plugins)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FireTrigger(self, request, context):
        """Fire a custom trigger (for trigger plugins)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPluginSelfConfig(self, request, context):
        """Get plugin's own config
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PluginLog(self, request, context):
        """Log a message (forwarded to daemon log buffer)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDaemonInfo(self, request, context):
        """Get daemon info (version, state, port)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginHostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=plugin__pb2.PluginRegisterRequest.FromString,
                    response_serializer=plugin__pb2.PluginRegisterResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=plugin__pb2.PluginEventFilter.FromString,
                    response_serializer=plugin__pb2.PluginEventMsg.SerializeToString,
            ),
            'SendChatMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.SendChatMessage,
                    request_deserializer=plugin__pb2.PluginChatRequest.FromString,
                    response_serializer=plugin__pb2.PluginChatChunk.SerializeToString,
            ),
            'FireTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.FireTrigger,
                    request_deserializer=plugin__pb2.PluginFireTriggerRequest.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'GetPluginSelfConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPluginSelfConfig,
                    request_deserializer=plugin__pb2.PluginSelfIdRequest.FromString,
                    response_serializer=plugin__pb2.PluginSelfConfigResponse.SerializeToString,
            ),
            'PluginLog': grpc.unary_unary_rpc_method_handler(
                    servicer.PluginLog,
                    request_deserializer=plugin__pb2.PluginLogRequest.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'GetDaemonInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDaemonInfo,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.PluginDaemonInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'astra.PluginHostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('astra.PluginHostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginHostService(object):
    """============ Plugin Host Service (daemon exposes, plugins call into) ============

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginHostService/Register',
            plugin__pb2.PluginRegisterRequest.SerializeToString,
            plugin__pb2.PluginRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/astra.PluginHostService/SubscribeEvents',
            plugin__pb2.PluginEventFilter.SerializeToString,
            plugin__pb2.PluginEventMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendChatMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/astra.PluginHostService/SendChatMessage',
            plugin__pb2.PluginChatRequest.SerializeToString,
            plugin__pb2.PluginChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FireTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginHostService/FireTrigger',
            plugin__pb2.PluginFireTriggerRequest.SerializeToString,
            plugin__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPluginSelfConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginHostService/GetPluginSelfConfig',
            plugin__pb2.PluginSelfIdRequest.SerializeToString,
            plugin__pb2.PluginSelfConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PluginLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginHostService/PluginLog',
            plugin__pb2.PluginLogRequest.SerializeToString,
            plugin__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDaemonInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginHostService/GetDaemonInfo',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.PluginDaemonInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PluginCapabilityServiceStub(object):
    """============ Plugin Capability Service (plugin exposes, daemon calls) ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTools = channel.unary_unary(
                '/astra.PluginCapabilityService/ListTools',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.PluginToolListResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/astra.PluginCapabilityService/CallTool',
                request_serializer=plugin__pb2.PluginCallToolRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginCallToolResponse.FromString,
                _registered_method=True)
        self.TtsSynthesize = channel.unary_unary(
                '/astra.PluginCapabilityService/TtsSynthesize',
                request_serializer=plugin__pb2.PluginTtsSynthesizeRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginTtsSynthesizeResponse.FromString,
                _registered_method=True)
        self.TtsSynthesizeStream = channel.unary_stream(
                '/astra.PluginCapabilityService/TtsSynthesizeStream',
                request_serializer=plugin__pb2.PluginTtsSynthesizeRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginAudioChunk.FromString,
                _registered_method=True)
        self.TtsListVoices = channel.unary_unary(
                '/astra.PluginCapabilityService/TtsListVoices',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.PluginTtsVoicesResponse.FromString,
                _registered_method=True)
        self.SttProcess = channel.stream_stream(
                '/astra.PluginCapabilityService/SttProcess',
                request_serializer=plugin__pb2.PluginAudioChunk.SerializeToString,
                response_deserializer=plugin__pb2.PluginSttEvent.FromString,
                _registered_method=True)
        self.SttGetLanguages = channel.unary_unary(
                '/astra.PluginCapabilityService/SttGetLanguages',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.PluginSttLanguagesResponse.FromString,
                _registered_method=True)
        self.AiComplete = channel.unary_stream(
                '/astra.PluginCapabilityService/AiComplete',
                request_serializer=plugin__pb2.PluginAiCompleteRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginAiStreamChunk.FromString,
                _registered_method=True)
        self.AiGetModels = channel.unary_unary(
                '/astra.PluginCapabilityService/AiGetModels',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.PluginAiModelsResponse.FromString,
                _registered_method=True)
        self.ExecuteAction = channel.unary_unary(
                '/astra.PluginCapabilityService/ExecuteAction',
                request_serializer=plugin__pb2.PluginExecuteActionRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginExecuteActionResponse.FromString,
                _registered_method=True)
        self.GetPluginActionTypes = channel.unary_unary(
                '/astra.PluginCapabilityService/GetPluginActionTypes',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.PluginActionTypesResponse.FromString,
                _registered_method=True)
        self.GetPluginTriggerTypes = channel.unary_unary(
                '/astra.PluginCapabilityService/GetPluginTriggerTypes',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.PluginTriggerTypesResponse.FromString,
                _registered_method=True)
        self.GetUiPanels = channel.unary_unary(
                '/astra.PluginCapabilityService/GetUiPanels',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.PluginUiPanelsResponse.FromString,
                _registered_method=True)
        self.OnConfigChanged = channel.unary_unary(
                '/astra.PluginCapabilityService/OnConfigChanged',
                request_serializer=plugin__pb2.PluginConfigChangedMsg.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                _registered_method=True)
        self.OnActiveTriggers = channel.unary_unary(
                '/astra.PluginCapabilityService/OnActiveTriggers',
                request_serializer=plugin__pb2.PluginActiveTriggersMsg.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/astra.PluginCapabilityService/Shutdown',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/astra.PluginCapabilityService/HealthCheck',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.PluginHealthResponse.FromString,
                _registered_method=True)


class PluginCapabilityServiceServicer(object):
    """============ Plugin Capability Service (plugin exposes, daemon calls) ============

    """

    def ListTools(self, request, context):
        """-- Tools --
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TtsSynthesize(self, request, context):
        """-- TTS --
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TtsSynthesizeStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TtsListVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SttProcess(self, request_iterator, context):
        """-- STT --
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SttGetLanguages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AiComplete(self, request, context):
        """-- AI Provider --
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AiGetModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAction(self, request, context):
        """-- Actions --
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPluginActionTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPluginTriggerTypes(self, request, context):
        """-- Triggers --
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUiPanels(self, request, context):
        """-- UI --
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnConfigChanged(self, request, context):
        """-- Lifecycle --
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnActiveTriggers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginCapabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.PluginToolListResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=plugin__pb2.PluginCallToolRequest.FromString,
                    response_serializer=plugin__pb2.PluginCallToolResponse.SerializeToString,
            ),
            'TtsSynthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.TtsSynthesize,
                    request_deserializer=plugin__pb2.PluginTtsSynthesizeRequest.FromString,
                    response_serializer=plugin__pb2.PluginTtsSynthesizeResponse.SerializeToString,
            ),
            'TtsSynthesizeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.TtsSynthesizeStream,
                    request_deserializer=plugin__pb2.PluginTtsSynthesizeRequest.FromString,
                    response_serializer=plugin__pb2.PluginAudioChunk.SerializeToString,
            ),
            'TtsListVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.TtsListVoices,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.PluginTtsVoicesResponse.SerializeToString,
            ),
            'SttProcess': grpc.stream_stream_rpc_method_handler(
                    servicer.SttProcess,
                    request_deserializer=plugin__pb2.PluginAudioChunk.FromString,
                    response_serializer=plugin__pb2.PluginSttEvent.SerializeToString,
            ),
            'SttGetLanguages': grpc.unary_unary_rpc_method_handler(
                    servicer.SttGetLanguages,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.PluginSttLanguagesResponse.SerializeToString,
            ),
            'AiComplete': grpc.unary_stream_rpc_method_handler(
                    servicer.AiComplete,
                    request_deserializer=plugin__pb2.PluginAiCompleteRequest.FromString,
                    response_serializer=plugin__pb2.PluginAiStreamChunk.SerializeToString,
            ),
            'AiGetModels': grpc.unary_unary_rpc_method_handler(
                    servicer.AiGetModels,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.PluginAiModelsResponse.SerializeToString,
            ),
            'ExecuteAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAction,
                    request_deserializer=plugin__pb2.PluginExecuteActionRequest.FromString,
                    response_serializer=plugin__pb2.PluginExecuteActionResponse.SerializeToString,
            ),
            'GetPluginActionTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPluginActionTypes,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.PluginActionTypesResponse.SerializeToString,
            ),
            'GetPluginTriggerTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPluginTriggerTypes,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.PluginTriggerTypesResponse.SerializeToString,
            ),
            'GetUiPanels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUiPanels,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.PluginUiPanelsResponse.SerializeToString,
            ),
            'OnConfigChanged': grpc.unary_unary_rpc_method_handler(
                    servicer.OnConfigChanged,
                    request_deserializer=plugin__pb2.PluginConfigChangedMsg.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'OnActiveTriggers': grpc.unary_unary_rpc_method_handler(
                    servicer.OnActiveTriggers,
                    request_deserializer=plugin__pb2.PluginActiveTriggersMsg.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.PluginHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'astra.PluginCapabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('astra.PluginCapabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginCapabilityService(object):
    """============ Plugin Capability Service (plugin exposes, daemon calls) ============

    """

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/ListTools',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.PluginToolListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/CallTool',
            plugin__pb2.PluginCallToolRequest.SerializeToString,
            plugin__pb2.PluginCallToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TtsSynthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/TtsSynthesize',
            plugin__pb2.PluginTtsSynthesizeRequest.SerializeToString,
            plugin__pb2.PluginTtsSynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TtsSynthesizeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/astra.PluginCapabilityService/TtsSynthesizeStream',
            plugin__pb2.PluginTtsSynthesizeRequest.SerializeToString,
            plugin__pb2.PluginAudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TtsListVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/TtsListVoices',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.PluginTtsVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SttProcess(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/astra.PluginCapabilityService/SttProcess',
            plugin__pb2.PluginAudioChunk.SerializeToString,
            plugin__pb2.PluginSttEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SttGetLanguages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/SttGetLanguages',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.PluginSttLanguagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AiComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/astra.PluginCapabilityService/AiComplete',
            plugin__pb2.PluginAiCompleteRequest.SerializeToString,
            plugin__pb2.PluginAiStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AiGetModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/AiGetModels',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.PluginAiModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/ExecuteAction',
            plugin__pb2.PluginExecuteActionRequest.SerializeToString,
            plugin__pb2.PluginExecuteActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPluginActionTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/GetPluginActionTypes',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.PluginActionTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPluginTriggerTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/GetPluginTriggerTypes',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.PluginTriggerTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUiPanels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/GetUiPanels',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.PluginUiPanelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnConfigChanged(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/OnConfigChanged',
            plugin__pb2.PluginConfigChangedMsg.SerializeToString,
            plugin__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnActiveTriggers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/OnActiveTriggers',
            plugin__pb2.PluginActiveTriggersMsg.SerializeToString,
            plugin__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/Shutdown',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.PluginCapabilityService/HealthCheck',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.PluginHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
