// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (C) 2026 Minice — https://minice.ai

//! Plugin runner — CLI args, gRPC server, registration, lifecycle, shutdown.
//!
//! # Startup order
//!
//! ```text
//! bind  →  register  →  build ctx  →  on_config  →  on_language_changed
//!       →  on_start  →  serve
//! ```
//!
//! Each step depends on the one before it and on nothing after it, which is the
//! only reason the order is fixed. `bind` comes before `register` because the
//! daemon is told the port during `Register` and may call back immediately —
//! the listener is up, so those calls queue in the accept backlog instead of
//! being refused. `on_config` and `on_language_changed` come before `on_start`
//! because a plugin that starts a background loop needs its settings first;
//! before 0.6 they ran in the other order and every example worked around it.
//! `on_start` comes before `serve` because an `Err` there **aborts startup**:
//! a plugin that cannot do its job must not be a plugin the daemon believes is
//! healthy.

use std::net::SocketAddr;
use std::sync::{Arc, Mutex};

use anyhow::{Context, Result};
use clap::Parser;
use tokio::net::TcpListener;
use tokio::signal;
use tokio::sync::oneshot;
use tokio::task::JoinHandle;
use tonic::transport::Server;
use tracing::{info, warn};

use crate::auth::{CapabilityAuth, CapabilityInterceptor};
use crate::capability::{AiChunk, AudioChunk, PluginCapability, SttEvent, TtsRequest};
use crate::context::{Host, PluginContext, install_context};
use crate::error::{ToolError, hook_status};
use crate::events;
use crate::host_client::HostClient;
use crate::proto;
use crate::proto::plugin_capability_service_server::PluginCapabilityServiceServer;

/// Dispatch a daemon event to the appropriate typed handler on the plugin.
/// Also always calls `on_event()` for the raw payload.
///
/// `pub(crate)` so the level-1 test harness delivers events through the same
/// code the runner does — a harness with its own dispatch would be testing
/// itself.
pub(crate) async fn dispatch_event<P: PluginCapability>(
    plugin: &P,
    ctx: &PluginContext,
    event: &proto::PluginEventMsg,
) {
    match event.event_type.as_str() {
        "state_changed" => {
            if let Ok(parsed) = serde_json::from_str::<events::StateChangedEvent>(&event.payload_json) {
                plugin.on_state_changed(ctx, parsed).await;
            }
        }
        "command_triggered" => {
            if let Ok(parsed) = serde_json::from_str::<events::CommandTriggeredEvent>(&event.payload_json) {
                plugin.on_command_triggered(ctx, parsed).await;
            }
        }
        "command_completed" => {
            if let Ok(parsed) = serde_json::from_str::<events::CommandCompletedEvent>(&event.payload_json) {
                plugin.on_command_completed(ctx, parsed).await;
            }
        }
        _ => {}
    }
    plugin.on_event(ctx, &event.event_type, &event.payload_json).await;
}

/// CLI arguments passed by the Astra daemon when spawning a plugin.
#[derive(Parser, Debug)]
#[command(name = "astra-plugin")]
struct Args {
    /// Daemon gRPC address (host:port).
    #[arg(long)]
    daemon_addr: String,

    /// Plugin ID (from manifest).
    #[arg(long)]
    plugin_id: String,

    /// Auth token for registration verification (generated by daemon).
    #[arg(long, default_value = "")]
    auth_token: String,

    /// The `[capabilities]` this plugin's manifest declares, comma-separated.
    ///
    /// The daemon reads `plugin.toml` — which it, not the plugin, can locate —
    /// and passes the result here.
    #[arg(long, value_delimiter = ',')]
    capabilities: Vec<String>,
}

/// The flags the daemon spawns a plugin with. Everything else on the command
/// line belongs to the plugin.
const DAEMON_FLAGS: &[&str] = &[
    "--daemon-addr",
    "--plugin-id",
    "--auth-token",
    "--capabilities",
];

/// Ask a plugin binary what capabilities it was built with, one per line, and
/// exit 0. Used by `astra-plugin check` to cross-check the manifest against the
/// binary without a daemon; emitted by `#[astra::plugin]`, which knows the
/// answer at compile time.
const PRINT_CAPABILITIES_FLAG: &str = "--print-capabilities";

/// Keep only the daemon's own flags out of `argv`.
///
/// A plugin is a normal binary and may define its own CLI (`--verbose`, a
/// subcommand, …). `Args::parse()` would abort the whole process on the first
/// argument it does not know, so the SDK filters argv down to what it owns and
/// silently leaves the rest to the plugin.
fn daemon_args(argv: impl IntoIterator<Item = String>) -> Vec<String> {
    let mut argv = argv.into_iter();
    let mut out = vec![argv.next().unwrap_or_else(|| "astra-plugin".to_string())];

    while let Some(arg) = argv.next() {
        if let Some((flag, _)) = arg.split_once('=')
            && DAEMON_FLAGS.contains(&flag)
        {
            out.push(arg);
        } else if DAEMON_FLAGS.contains(&arg.as_str()) {
            // `--flag value` — take the value with it, or the flag alone if the
            // caller truncated it (clap reports the missing value).
            out.push(arg);
            if let Some(value) = argv.next() {
                out.push(value);
            }
        }
    }

    out
}

/// The environment variable the daemon states `[capabilities]` in.
///
/// **The daemon uses the environment and not argv, and the reason is a
/// compatibility bug that would have been ours.** The list was briefly appended
/// as `--capabilities=<list>`, on the reasoning that a plugin binary already in
/// the field scans argv for the prefixes it knows and ignores the rest. True of
/// this SDK ([`daemon_args`] filters argv down to the flags it owns) and of the
/// TypeScript one — and false of the published Python SDK 0.4.0, which parses
/// argv with `argparse.parse_args()` and exits 2 on an unrecognised argument
/// before it ever binds its port. A variable a process does not read cannot
/// break it, so that is the channel.
///
/// Present-but-empty means "this manifest declares none". *Absent* means the
/// daemon predates §5.4 — see [`resolve_capabilities`].
const CAPABILITIES_ENV: &str = "ASTRA_PLUGIN_CAPABILITIES";

/// What the daemon stated in the environment, or `None` if it stated nothing.
///
/// `Some(vec![])` and `None` are different answers and the difference matters:
/// the first is "you were granted nothing", the second is "nobody told me".
fn capabilities_from_env() -> Option<Vec<String>> {
    std::env::var(CAPABILITIES_ENV)
        .ok()
        .map(|v| v.split(',').map(|s| s.trim().to_string()).collect())
}

/// Decide what capability list to send at registration.
///
/// **The manifest is the source of truth, and the plugin cannot read it.** In a
/// packaged bundle `plugin.toml` sits at the install root while the executable
/// is under `bin/`, so `std::env::current_exe().parent().join("plugin.toml")` —
/// what every "just read the manifest" design ends up as — finds nothing. The
/// daemon has already parsed the manifest to decide whether to spawn this
/// process at all, so it passes the answer down.
///
/// The order is: an explicit `--capabilities` on argv (no daemon sends one
/// today, but a harness or a `dev` sideload may), else
/// [`CAPABILITIES_ENV`], else what the binary was built to declare
/// ([`RunConfig::capabilities`], which `#[astra::plugin]` fills in), else
/// nothing plus a warning. It is never *inferred* from which trait methods
/// return non-empty vectors — that was 0.5's `discover_capabilities`, and it
/// made a plugin's capability set depend on whether a list happened to be empty
/// at startup, silently disagreeing with the manifest the user consented to.
fn resolve_capabilities(
    from_argv: Vec<String>,
    from_env: Option<Vec<String>>,
    declared: &[String],
) -> Vec<String> {
    let clean = |v: Vec<String>| -> Vec<String> {
        v.into_iter()
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .collect()
    };

    let from_argv = clean(from_argv);
    if !from_argv.is_empty() {
        return from_argv;
    }
    // `Some` is the daemon speaking, even when the list is empty: this manifest
    // declares nothing, and falling back to what the binary was built with would
    // override the file the user actually consented to.
    if let Some(stated) = from_env {
        let stated = clean(stated);
        if stated.is_empty() {
            warn!(
                "The daemon says this plugin's manifest declares no capabilities. \
                 No hook will be called. Add a `[capabilities]` section to \
                 plugin.toml."
            );
        }
        return stated;
    }
    let declared = clean(declared.to_vec());
    if !declared.is_empty() {
        warn!(
            "The daemon stated no capabilities ({CAPABILITIES_ENV} is unset); \
             falling back to the {} this binary declares. An Astra older than \
             the one this SDK targets does not state them.",
            declared.len()
        );
        return declared;
    }
    warn!(
        "Registering with NO capabilities: the daemon stated none and this \
         binary declares none. The daemon will not call any hook. Pass \
         RunConfig::capabilities, or use #[astra::plugin], which fills it in."
    );
    Vec::new()
}

/// Optional knobs for [`run_with`].
///
/// Constructed with `RunConfig::default()` and adjusted field by field; it is
/// `#[non_exhaustive]` so new knobs are not breaking changes.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct RunConfig {
    /// Install the SDK's `tracing_subscriber`. Leave `true` unless the plugin
    /// installs its own — the SDK uses `try_init`, so a subscriber the plugin
    /// set up first simply wins and this is a no-op.
    pub init_tracing: bool,

    /// Argv to parse instead of `std::env::args()`.
    pub argv: Option<Vec<String>>,

    /// Address the plugin's gRPC server binds. Port 0 means OS-assigned; the
    /// bound port is what gets reported to the daemon at registration.
    ///
    /// SECURITY: loopback only. Loopback is not a boundary between processes of
    /// the same user, so it is `capability_auth` — not this address — that keeps
    /// another local process out of the plugin's tools.
    pub bind_addr: SocketAddr,

    /// How strictly the plugin's capability server checks that an inbound call
    /// really came from the daemon that spawned it.
    ///
    /// See [`CapabilityAuth`]. The `ASTRA_PLUGIN_CAPABILITY_AUTH` environment
    /// variable overrides whatever is set here, so an operator can enforce (or
    /// disable) the check without rebuilding the plugin.
    pub capability_auth: CapabilityAuth,

    /// The capabilities this binary was built to serve — the fallback when the
    /// daemon passes no `--capabilities`, and the answer to
    /// `--print-capabilities`.
    ///
    /// The daemon's list always wins: it read the manifest, which is the thing
    /// the user consented to. This is what an Astra too old to send the flag
    /// falls back to.
    pub capabilities: Vec<String>,
}

impl Default for RunConfig {
    fn default() -> Self {
        Self {
            init_tracing: true,
            argv: None,
            bind_addr: SocketAddr::from(([127, 0, 0, 1], 0)),
            capability_auth: CapabilityAuth::default(),
            capabilities: Vec::new(),
        }
    }
}

/// Run a plugin. Call this from your `main()`.
///
/// Returns `Err` if binding, registration, `on_start` or serving fails —
/// propagate it out of `main` so the exit code is non-zero and the daemon sees
/// the failure.
pub async fn run<P: PluginCapability>(plugin: P) -> Result<()> {
    run_with(plugin, RunConfig::default()).await
}

/// [`run`] with explicit configuration.
pub async fn run_with<P: PluginCapability>(plugin: P, config: RunConfig) -> Result<()> {
    // Before anything that can panic — including the argument parse. A panic
    // the hook was not installed for is one nobody can read afterwards.
    crate::panics::install_hook();

    if config.init_tracing {
        use tracing_subscriber::layer::SubscriberExt;
        use tracing_subscriber::util::SubscriberInitExt;
        // `try_init`, not `init`: a plugin that installed its own subscriber (or
        // a second `run_with` in one process, as in tests) must not panic here.
        //
        // Two layers: stderr, which the daemon captures, and the host layer,
        // which turns the author's own `tracing::info!` into a `PluginLog` the
        // *user* can read in the plugin's log pane. It is inert until
        // `logging::attach` hands it a host client, below.
        let _ = tracing_subscriber::registry()
            .with(
                tracing_subscriber::EnvFilter::try_from_default_env()
                    .unwrap_or_else(|_| "info".into()),
            )
            .with(tracing_subscriber::fmt::layer())
            .with(crate::logging::layer())
            .try_init();
    }

    let argv = config
        .argv
        .clone()
        .unwrap_or_else(|| std::env::args().collect::<Vec<_>>());

    // Answered before anything else: `--print-capabilities` is a question about
    // the binary, not a request to run it, and it must work with no daemon,
    // no --plugin-id and no network.
    if argv.iter().any(|a| a == PRINT_CAPABILITIES_FLAG) {
        for cap in &config.capabilities {
            println!("{cap}");
        }
        return Ok(());
    }

    let args = Args::parse_from(daemon_args(argv));
    info!(
        "Starting plugin '{}', connecting to daemon at {}",
        args.plugin_id, args.daemon_addr
    );

    let plugin = Arc::new(plugin);

    // ── bind ──
    // Before registering: the daemon is told the port during Register and may
    // call back immediately.
    let listener = TcpListener::bind(config.bind_addr)
        .await
        .with_context(|| format!("Failed to bind {}", config.bind_addr))?;
    let local_addr: SocketAddr = listener.local_addr()?;
    let port = local_addr.port();
    info!("Plugin gRPC server listening on port {}", port);

    // ── register ──
    // `connect_bootstrap` can only Register; `register` consumes it and returns
    // the client that carries the session token.
    let bootstrap = HostClient::connect_bootstrap(&args.daemon_addr, args.plugin_id.clone()).await?;

    let capabilities = resolve_capabilities(
        args.capabilities,
        capabilities_from_env(),
        &config.capabilities,
    );
    info!("Registering with capabilities: {:?}", capabilities);
    let is_client_plugin =
        plugin.is_client() || capabilities.iter().any(|c| c == "client");

    let (host, reg_response) = match bootstrap
        .register(port, capabilities, args.auth_token.clone())
        .await
    {
        Ok(pair) => pair,
        Err(e) => {
            // A protocol mismatch is not a fault to retry, log a backtrace for,
            // or bury in a `Result` the caller turns into "plugin exited 1". It
            // is one fact with one fix. Say it on stderr — where the daemon
            // captures plugin output and the user reads it in the plugin's log
            // pane — and leave with EX_CONFIG.
            if let Some(mismatch) = e.downcast_ref::<crate::protocol::ProtocolMismatch>() {
                eprintln!("{mismatch}");
                std::process::exit(crate::protocol::EXIT_PROTOCOL_INCOMPATIBLE);
            }
            return Err(e);
        }
    };
    info!(
        "Registered successfully. Daemon version: {}, protocol: {} (accepts {}+)",
        reg_response.daemon_version, reg_response.protocol_version, reg_response.min_supported_protocol
    );

    // ── build ctx ──
    let host = Arc::new(host);

    // From here on, `tracing::warn!("…")` in the plugin's own code reaches the
    // user's log pane and not just stderr. Registration is the earliest this
    // can happen: before it there is no authenticated client to send on.
    crate::logging::attach(host.clone() as Arc<dyn Host>);

    let mut ctx = PluginContext::new(args.plugin_id.clone(), host.clone() as Arc<dyn Host>);

    // Background loops (chat firehose, event subscription). Kept so shutdown
    // stops them instead of leaving them running against a dead host client.
    let mut background: Vec<JoinHandle<()>> = Vec::new();

    // A client-capable plugin gets the full daemon API. Gated on the capability,
    // not on the token being non-empty: the daemon issues a session token to
    // EVERY plugin (host_service.rs, SECURITY(B1)) because every host RPC needs
    // one, so an empty-token test says nothing about capability.
    if is_client_plugin && !reg_response.client_session_token.is_empty() {
        let daemon_client = crate::DaemonClient::connect(
            &args.daemon_addr,
            reg_response.client_session_token.clone(),
        )
        .await?;
        ctx = ctx.with_daemon(Arc::new(daemon_client));
        info!("DaemonClient connected (plugin has client capability)");
    }

    if !reg_response.language.is_empty() {
        ctx.set_language(reg_response.language.clone());
    }

    // Published for background tasks that cannot be handed a parameter — see
    // `crate::ctx()`. Handlers are given `&PluginContext` and should use that.
    install_context(ctx.clone());

    // ── on_config ──
    // Before on_start, so a plugin that starts a background loop has its
    // settings. `on_config_changed` defaults to parse-then-delegate.
    if !reg_response.config_json.is_empty() {
        plugin.on_config_changed(&ctx, &reg_response.config_json).await;
    }

    // ── on_language_changed ──
    if !reg_response.language.is_empty() {
        plugin.on_language_changed(&ctx, &reg_response.language).await;
    }

    // ── on_start ──
    // An Err here aborts startup. The plugin never serves and the process exits
    // non-zero, which is what the daemon needs to see.
    // A panic here is still an aborted startup — but it arrives as one
    // sentence naming `on_start` and the line, rather than as an unwind out of
    // `main` that the daemon reads as "exited 101".
    match crate::panics::catch("on_start", plugin.on_start(&ctx)).await {
        Ok(res) => res.context("Plugin on_start failed; aborting startup")?,
        Err(panicked) => {
            return Err(anyhow::anyhow!("{panicked}")
                .context("Plugin on_start panicked; aborting startup"));
        }
    }

    // Firehose loop: on_conversation_event for every chat event. Fetch the
    // conversation list first and subscribe with cursor=0 for each so plugins
    // receive the full event history on startup in addition to live events.
    if let Some(daemon) = ctx.daemon().cloned() {
        let plugin_for_chat = plugin.clone();
        let ctx_for_chat = ctx.clone();
        background.push(tokio::spawn(async move {
            loop {
                let cursors: std::collections::HashMap<String, u64> =
                    match daemon.list_conversations().await {
                        Ok(resp) => resp
                            .conversations
                            .iter()
                            .map(|c| (c.id.clone(), 0u64))
                            .collect(),
                        Err(e) => {
                            tracing::warn!("list_conversations failed: {e}");
                            std::collections::HashMap::new()
                        }
                    };
                match daemon.subscribe_chat_events(cursors).await {
                    Ok(mut stream) => {
                        info!("Chat firehose active");
                        use tokio_stream::StreamExt;
                        while let Some(msg) = stream.next().await {
                            match msg {
                                Ok(fe) => {
                                    if let Some(event) = fe.event {
                                        plugin_for_chat
                                            .on_conversation_event(
                                                &ctx_for_chat,
                                                &fe.conversation_id,
                                                &event,
                                            )
                                            .await;
                                    }
                                }
                                Err(e) => {
                                    tracing::warn!("Chat firehose error: {e}, will reconnect");
                                    break;
                                }
                            }
                        }
                        info!("Chat firehose stream ended, reconnecting...");
                    }
                    Err(e) => {
                        tracing::warn!("Chat firehose subscribe failed: {e}, retrying...");
                    }
                }
                tokio::time::sleep(std::time::Duration::from_secs(2)).await;
            }
        }));
    }

    // Start daemon-event subscription if the plugin wants host-level events.
    // Chat events are NOT here — they come via the firehose above.
    let event_types = plugin.subscribed_events();
    if !event_types.is_empty() {
        info!("Subscribing to daemon events: {:?}", event_types);
        let plugin_for_events = plugin.clone();
        let ctx_for_events = ctx.clone();
        let host_for_events = host.clone();
        background.push(tokio::spawn(async move {
            loop {
                match host_for_events
                    .subscribe_events(event_types.clone(), String::new())
                    .await
                {
                    Ok(mut stream) => {
                        info!("Event subscription active");
                        use tokio_stream::StreamExt;
                        while let Some(msg) = stream.next().await {
                            match msg {
                                Ok(event) => {
                                    dispatch_event(&*plugin_for_events, &ctx_for_events, &event)
                                        .await;
                                }
                                Err(e) => {
                                    tracing::warn!("Event stream error: {e}, will reconnect");
                                    break;
                                }
                            }
                        }
                        info!("Event subscription stream ended, reconnecting...");
                    }
                    Err(e) => {
                        tracing::warn!("Event subscription failed: {e}, retrying...");
                    }
                }
                tokio::time::sleep(std::time::Duration::from_secs(2)).await;
            }
        }));
    }

    // ── serve ──
    // The oneshot below is the single shutdown path: signals and the daemon's
    // `Shutdown` RPC both fire it, tonic then stops accepting and drains
    // in-flight requests (so `Shutdown` gets its reply), and `on_shutdown()`
    // runs exactly once after the server is down.
    let (shutdown_tx, shutdown_rx) = oneshot::channel::<()>();
    let shutdown = ShutdownTrigger::new(shutdown_tx);
    let svc = CapabilityServiceImpl {
        plugin: plugin.clone(),
        ctx: ctx.clone(),
        shutdown: shutdown.clone(),
    };

    // SECURITY: the capability server is the daemon's way into this plugin's
    // tools, config and shutdown, and loopback separates it from nothing — any
    // process of the same user can dial the port. The guard demands the daemon
    // hand back the spawn-time `--auth-token`, which only it and this process
    // know. Staged: see `CapabilityAuth`.
    let guard = CapabilityInterceptor::new(&args.auth_token, config.capability_auth.resolved());
    if !guard.is_active() {
        warn!(
            "Capability server is unauthenticated — any local process can call this plugin. \
             (No --auth-token was passed, or the check is switched off.)"
        );
    }
    let server = Server::builder()
        .add_service(PluginCapabilityServiceServer::with_interceptor(svc, guard))
        .serve_with_incoming_shutdown(
            tokio_stream::wrappers::TcpListenerStream::new(listener),
            async move {
                // A dropped sender (no trigger ever fired) also means "stop".
                let _ = shutdown_rx.await;
            },
        );

    let mut server_handle = tokio::spawn(server);

    // Serve until the server finishes on its own (daemon `Shutdown`, or an
    // error) or the process is asked to stop.
    tokio::select! {
        biased;
        res = &mut server_handle => return finish(&*plugin, &ctx, background, res).await,
        _ = signal::ctrl_c() => info!("SIGINT received, shutting down"),
        _ = terminate_signal() => info!("SIGTERM received, shutting down"),
    }

    shutdown.trigger();

    // Graceful shutdown drains in-flight requests — including server-streaming
    // ones (`stt_process`) that a busy plugin may hold open indefinitely. Give
    // them a bounded grace period, then stop waiting: a process asked to
    // terminate has to terminate.
    let res = match tokio::time::timeout(SHUTDOWN_GRACE, &mut server_handle).await {
        Ok(res) => res,
        Err(_) => {
            warn!(
                "gRPC server still draining after {}s — forcing shutdown",
                SHUTDOWN_GRACE.as_secs()
            );
            server_handle.abort();
            server_handle.await
        }
    };
    finish(&*plugin, &ctx, background, res).await
}

/// How long a shutdown waits for in-flight RPCs before forcing the issue.
///
/// Must not exceed the daemon's own grace (`spec/limits.yaml`), or the tidy
/// path never runs: the daemon kills the process group first.
const SHUTDOWN_GRACE: std::time::Duration =
    std::time::Duration::from_secs(crate::limits::PLUGIN_STOP_GRACE_SECS);

/// Stop the background loops, run `on_shutdown()`, and turn the server's exit
/// into this function's return value — a serve failure must surface as `Err`,
/// not as a silent exit 0.
async fn finish<P: PluginCapability>(
    plugin: &P,
    ctx: &PluginContext,
    background: Vec<JoinHandle<()>>,
    res: Result<Result<(), tonic::transport::Error>, tokio::task::JoinError>,
) -> Result<()> {
    for task in background {
        task.abort();
    }
    plugin.on_shutdown(ctx).await;

    match res {
        Ok(Ok(())) => {
            info!("Plugin shut down cleanly");
            Ok(())
        }
        Ok(Err(e)) => Err(anyhow::Error::new(e).context("Plugin gRPC server failed")),
        // Aborted after the grace period — a forced but intentional shutdown.
        Err(e) if e.is_cancelled() => {
            info!("Plugin shut down (server forcibly stopped)");
            Ok(())
        }
        Err(e) => Err(anyhow::Error::new(e).context("Plugin gRPC server task failed")),
    }
}

/// Resolves when the process receives `SIGTERM` — how the daemon (and every
/// service manager) asks a child to stop. Never resolves on non-Unix.
async fn terminate_signal() {
    #[cfg(unix)]
    {
        match signal::unix::signal(signal::unix::SignalKind::terminate()) {
            Ok(mut sig) => {
                sig.recv().await;
            }
            Err(e) => {
                warn!("Cannot listen for SIGTERM: {e}");
                std::future::pending::<()>().await;
            }
        }
    }
    #[cfg(not(unix))]
    {
        std::future::pending::<()>().await;
    }
}

/// Fire-once shutdown trigger, shared by the signal handlers and the daemon's
/// `Shutdown` RPC. The first caller closes the oneshot that
/// `serve_with_incoming_shutdown` waits on; later calls are no-ops.
#[derive(Clone)]
struct ShutdownTrigger(Arc<Mutex<Option<oneshot::Sender<()>>>>);

impl ShutdownTrigger {
    fn new(tx: oneshot::Sender<()>) -> Self {
        Self(Arc::new(Mutex::new(Some(tx))))
    }

    fn trigger(&self) {
        // A poisoned lock only means some other task panicked while taking the
        // sender; shutting down is still the right thing to do.
        let taken = self
            .0
            .lock()
            .unwrap_or_else(|e| e.into_inner())
            .take();
        if let Some(tx) = taken {
            let _ = tx.send(());
        }
    }
}

// ── gRPC service implementation that delegates to the PluginCapability trait ──

/// How many chunks a streaming hook may run ahead of the daemon. Small on
/// purpose: back-pressure onto a plugin that is generating faster than the
/// daemon consumes is correct, and a deep buffer only hides it.
const STREAM_CHANNEL_CAPACITY: usize = 16;

struct CapabilityServiceImpl<P: PluginCapability> {
    plugin: Arc<P>,
    ctx: PluginContext,
    shutdown: ShutdownTrigger,
}

/// Run one hook, turning a panic into a `Status` the daemon can log.
///
/// `INTERNAL`, never `UNIMPLEMENTED`: the daemon reads the latter as *this hook
/// is absent* and stops calling it for the life of the process, which would
/// turn one panic into a plugin that has quietly lost a capability.
async fn catch<F: std::future::Future>(
    hook: &str,
    fut: F,
) -> Result<F::Output, tonic::Status> {
    crate::panics::catch(hook, fut).await.map_err(Into::into)
}

/// Run one hook that already returns `Result<_, ToolError>`, turning a panic
/// into the same in-band error a returned `Err` would have been.
async fn caught_tool<T, F: std::future::Future<Output = Result<T, ToolError>>>(
    hook: &str,
    fut: F,
) -> Result<T, ToolError> {
    match crate::panics::catch(hook, fut).await {
        Ok(res) => res,
        Err(panicked) => Err(panicked.into()),
    }
}

/// An error that reached the daemon *after* the response stream opened. The
/// headers are already sent, so there is no status left to set — the protocol's
/// place for this is the stream's own error variant.
fn ai_error_chunk(error: ToolError) -> proto::PluginAiStreamChunk {
    proto::PluginAiStreamChunk {
        content: Some(proto::plugin_ai_stream_chunk::Content::Error(error.wire_string())),
        error_detail: Some(error.to_plugin_error()),
    }
}

#[tonic::async_trait]
impl<P: PluginCapability> proto::plugin_capability_service_server::PluginCapabilityService
    for CapabilityServiceImpl<P>
{
    // ── Tools ──

    async fn list_tools(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::PluginToolListResponse>, tonic::Status> {
        let tools = catch("list_tools", self.plugin.list_tools()).await?;
        Ok(tonic::Response::new(proto::PluginToolListResponse {
            tools: tools.into_iter().map(Into::into).collect(),
        }))
    }

    async fn call_tool(
        &self,
        request: tonic::Request<proto::PluginCallToolRequest>,
    ) -> Result<tonic::Response<proto::PluginCallToolResponse>, tonic::Status> {
        let req = request.into_inner();
        // In-band, not `Status`: a tool that failed still ANSWERED, and the AI
        // loop has to read the answer. `wire_string()` prefixes the stable code
        // so "NOT_CONFIGURED" survives the trip through a `string error` field.
        //
        // A panic is one of those answers. `catch` turns it into
        // `ToolError::Internal`, so a bad `unwrap` in one tool costs that call
        // and not the process — every other capability this plugin serves is
        // still up when the next request arrives.
        let resp = match caught_tool(
            "call_tool",
            self.plugin
                .call_tool(&self.ctx, &req.tool_name, &req.arguments_json),
        )
        .await
        {
            Ok(result) => proto::PluginCallToolResponse {
                success: true,
                result,
                error: String::new(),
                error_detail: None,
            },
            // Both halves, always: `error_detail` is what the UI deep-links
            // from, and `error` is what an older daemon — and the model — read.
            Err(e) => proto::PluginCallToolResponse {
                success: false,
                result: String::new(),
                error: e.wire_string(),
                error_detail: Some(e.to_plugin_error()),
            },
        };
        Ok(tonic::Response::new(resp))
    }

    // ── TTS ──

    async fn tts_synthesize(
        &self,
        request: tonic::Request<proto::PluginTtsSynthesizeRequest>,
    ) -> Result<tonic::Response<proto::PluginTtsSynthesizeResponse>, tonic::Status> {
        let req: TtsRequest = request.into_inner().into();
        match catch("tts_synthesize", self.plugin.tts_synthesize(&self.ctx, req)).await? {
            Ok(audio) => Ok(tonic::Response::new(audio.into())),
            Err(e) => Err(hook_status(e)),
        }
    }

    type TtsSynthesizeStreamStream = std::pin::Pin<
        Box<dyn tokio_stream::Stream<Item = Result<proto::PluginAudioChunk, tonic::Status>> + Send>,
    >;

    async fn tts_synthesize_stream(
        &self,
        request: tonic::Request<proto::PluginTtsSynthesizeRequest>,
    ) -> Result<tonic::Response<Self::TtsSynthesizeStreamStream>, tonic::Status> {
        let req: TtsRequest = request.into_inner().into();
        let (tx, mut rx) = tokio::sync::mpsc::channel::<AudioChunk>(STREAM_CHANNEL_CAPACITY);
        let plugin = self.plugin.clone();
        let ctx = self.ctx.clone();
        let task = tokio::spawn(async move { plugin.tts_synthesize_stream(&ctx, req, tx).await });

        // Wait for the first chunk before answering. A hook that has no TTS at
        // all fails immediately and drops the sender, so `recv` returns `None`
        // and the failure can still be a status — which is the only way
        // UNIMPLEMENTED (i.e. "this plugin has no such hook") can be said at
        // all. Once a chunk is out, the headers are sent and it is too late.
        let Some(first) = rx.recv().await else {
            return match task.await {
                Ok(Ok(())) => {
                    let empty: Self::TtsSynthesizeStreamStream = Box::pin(tokio_stream::empty());
                    Ok(tonic::Response::new(empty))
                }
                Ok(Err(e)) => Err(hook_status(e)),
                Err(e) => Err(tonic::Status::internal(format!(
                    "tts_synthesize_stream panicked: {e}"
                ))),
            };
        };

        let out = async_stream::stream! {
            yield Ok::<proto::PluginAudioChunk, tonic::Status>(first.into());
            while let Some(chunk) = rx.recv().await {
                yield Ok(chunk.into());
            }
            match task.await {
                Ok(Ok(())) => {}
                Ok(Err(e)) => yield Err(hook_status(e)),
                Err(e) => yield Err(tonic::Status::internal(format!(
                    "tts_synthesize_stream panicked: {e}"
                ))),
            }
        };
        Ok(tonic::Response::new(Box::pin(out)))
    }

    async fn tts_list_voices(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::PluginTtsVoicesResponse>, tonic::Status> {
        let voices = catch("tts_voices", self.plugin.tts_voices()).await?;
        Ok(tonic::Response::new(proto::PluginTtsVoicesResponse {
            voices: voices.into_iter().map(Into::into).collect(),
        }))
    }

    async fn tts_activate(
        &self,
        request: tonic::Request<proto::PluginTtsActivateRequest>,
    ) -> Result<tonic::Response<proto::PluginTtsActivateResponse>, tonic::Status> {
        let req = request.into_inner();
        match catch(
            "tts_activate",
            self.plugin.tts_activate(&self.ctx, req.cek, &req.voice_id),
        )
        .await?
        {
            Ok(()) => Ok(tonic::Response::new(proto::PluginTtsActivateResponse {})),
            Err(e) => Err(hook_status(e)),
        }
    }

    // ── STT ──

    type SttProcessStream = std::pin::Pin<
        Box<dyn tokio_stream::Stream<Item = Result<proto::PluginSttEvent, tonic::Status>> + Send>,
    >;

    async fn stt_process(
        &self,
        request: tonic::Request<tonic::Streaming<proto::PluginAudioChunk>>,
    ) -> Result<tonic::Response<Self::SttProcessStream>, tonic::Status> {
        let mut inbound = request.into_inner();

        // Set up the streaming bridge: a channel of `Vec<u8>` chunks
        // (f32 LE PCM, no sample-rate boundaries) flows from the inbound
        // gRPC stream into the plugin, and `SttEvent`s flow back out into
        // the outbound stream.
        //
        // Capacity comes from `spec/limits.yaml`, which the daemon's end of
        // this bridge asserts against at compile time — the two channels are in
        // series, so the smaller one is the real capacity. The old hardcoded 32
        // was that silent bottleneck: the worst-case wake-seed dump (~8 s of
        // 16 kHz audio in 1600-sample batches ≈ 80) plus live audio piling up
        // overflowed it, so STT only ever saw the first fraction of an
        // utterance — while both files carried a comment promising lockstep.
        let (audio_tx, audio_rx) = tokio::sync::mpsc::channel::<Vec<u8>>(
            crate::limits::STT_AUDIO_CHANNEL_CAPACITY as usize,
        );
        let (events_tx, events_rx) = tokio::sync::mpsc::channel::<SttEvent>(8);

        // Peek the first chunk to learn the sample rate and the per-utterance
        // decoding options before spawning the plugin task — both are on the
        // first chunk only, and `stt_transcribe_stream` needs them up front.
        let first = match inbound.message().await? {
            Some(c) => c,
            None => {
                // Empty stream — nothing to transcribe.
                let empty: Self::SttProcessStream = Box::pin(tokio_stream::empty());
                return Ok(tonic::Response::new(empty));
            }
        };
        let sample_rate = first.sample_rate;
        let options = first.options.unwrap_or_default();
        let first_is_last = first.is_last;
        if !first.data.is_empty() {
            let _ = audio_tx.send(first.data).await;
        }

        // Inbound forwarder: pump every subsequent `PluginAudioChunk`'s
        // `data` into the audio channel until `is_last` or end-of-stream,
        // then drop the sender to signal end-of-utterance.
        if !first_is_last {
            let inbound_tx = audio_tx.clone();
            tokio::spawn(async move {
                while let Ok(Some(chunk)) = inbound.message().await {
                    if !chunk.data.is_empty() && inbound_tx.send(chunk.data).await.is_err() {
                        break;
                    }
                    if chunk.is_last {
                        break;
                    }
                }
                drop(inbound_tx);
            });
        }
        drop(audio_tx);

        // Plugin task: run `stt_transcribe_stream`. Default impl buffers
        // and forwards to `stt_transcribe` — so a non-streaming plugin
        // works without changes. A streaming-capable plugin (echo-stt,
        // a future Vosk wrapper) overrides the hook and consumes chunks
        // live.
        let plugin = self.plugin.clone();
        let ctx = self.ctx.clone();
        let task = tokio::spawn(async move {
            plugin
                .stt_transcribe_stream(&ctx, audio_rx, events_tx, sample_rate, options)
                .await
        });

        // Outbound forwarder: map every `SttEvent` to a proto event on
        // the response stream. Closes when `events_tx` is dropped by the
        // plugin task — and then reports how that task ended.
        //
        // The hook's `Err` is part of the answer, not a log line. It used to be
        // `warn!`ed and dropped, which made a plugin that declares `stt` and
        // does not implement `stt_transcribe` answer `SttProcess` with OK and
        // zero events — while Python and TypeScript both answered
        // UNIMPLEMENTED. That broke the protocol's own forward-compat contract
        // ("Unimplemented means the hook is absent") in the language most
        // plugins are written in, and it swallowed genuine mid-utterance
        // recognizer failures with it: the user saw a moving waveform, no text,
        // and nothing in the daemon log.
        //
        // Yielded *after* the events rather than awaited before them, unlike
        // `TtsSynthesizeStream`: a non-streaming STT plugin emits nothing until
        // the utterance ends, so waiting for a first event before answering
        // would hold the response headers for the whole utterance. Zero events
        // followed by an `Err` reaches the client as the status anyway, because
        // no message has been sent yet.
        let out = async_stream::stream! {
            let mut events_rx = events_rx;
            while let Some(ev) = events_rx.recv().await {
                let proto_ev: proto::PluginSttEvent = ev.into();
                yield Ok::<proto::PluginSttEvent, tonic::Status>(proto_ev);
            }
            match task.await {
                Ok(Ok(())) => {}
                Ok(Err(e)) => yield Err(hook_status(e)),
                Err(e) => yield Err(tonic::Status::internal(format!(
                    "stt_transcribe_stream panicked: {e}"
                ))),
            }
        };
        Ok(tonic::Response::new(Box::pin(out)))
    }

    async fn stt_get_languages(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::PluginSttLanguagesResponse>, tonic::Status> {
        let langs = catch("stt_languages", self.plugin.stt_languages()).await?;
        Ok(tonic::Response::new(proto::PluginSttLanguagesResponse {
            languages: langs,
        }))
    }

    async fn stt_load(
        &self,
        request: tonic::Request<proto::SttLoadRequest>,
    ) -> Result<tonic::Response<proto::Empty>, tonic::Status> {
        match catch(
            "stt_load",
            self.plugin.stt_load(&self.ctx, request.into_inner().into()),
        )
        .await?
        {
            Ok(()) => Ok(tonic::Response::new(proto::Empty {})),
            Err(e) => Err(hook_status(e)),
        }
    }

    async fn stt_unload(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::Empty>, tonic::Status> {
        match catch("stt_unload", self.plugin.stt_unload(&self.ctx)).await? {
            Ok(()) => Ok(tonic::Response::new(proto::Empty {})),
            Err(e) => Err(hook_status(e)),
        }
    }

    async fn stt_get_load_state(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::SttLoadStateResponse>, tonic::Status> {
        match catch("stt_load_state", self.plugin.stt_load_state(&self.ctx)).await? {
            Ok(state) => Ok(tonic::Response::new(state.into())),
            Err(e) => Err(hook_status(e)),
        }
    }

    async fn tts_get_config_fields(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::PluginConfigFieldsResponse>, tonic::Status> {
        let fields = catch("tts_config_fields", self.plugin.tts_config_fields()).await?;
        Ok(tonic::Response::new(proto::PluginConfigFieldsResponse {
            config_fields: fields,
        }))
    }

    async fn stt_get_config_fields(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::PluginConfigFieldsResponse>, tonic::Status> {
        let fields = catch("stt_config_fields", self.plugin.stt_config_fields()).await?;
        Ok(tonic::Response::new(proto::PluginConfigFieldsResponse {
            config_fields: fields,
        }))
    }

    // ── AI Provider ──

    type AiCompleteStream = std::pin::Pin<
        Box<
            dyn tokio_stream::Stream<Item = Result<proto::PluginAiStreamChunk, tonic::Status>>
                + Send,
        >,
    >;

    async fn ai_complete(
        &self,
        request: tonic::Request<proto::PluginAiCompleteRequest>,
    ) -> Result<tonic::Response<Self::AiCompleteStream>, tonic::Status> {
        let req = request.into_inner();
        let (tx, mut rx) = tokio::sync::mpsc::channel::<AiChunk>(STREAM_CHANNEL_CAPACITY);
        let plugin = self.plugin.clone();
        let ctx = self.ctx.clone();
        let task = tokio::spawn(async move { plugin.ai_complete(&ctx, req, tx).await });

        // Same first-chunk rule as `tts_synthesize_stream`: a plugin that is not
        // an AI provider has to be able to say `UNIMPLEMENTED`, and a status can
        // only be set before the first chunk goes out.
        let Some(first) = rx.recv().await else {
            return match task.await {
                Ok(Ok(())) => {
                    let done: Self::AiCompleteStream =
                        Box::pin(tokio_stream::once(Ok(AiChunk::Done.into())));
                    Ok(tonic::Response::new(done))
                }
                Ok(Err(e)) => Err(hook_status(e)),
                Err(e) => Err(tonic::Status::internal(format!("ai_complete panicked: {e}"))),
            };
        };

        let out = async_stream::stream! {
            yield Ok::<proto::PluginAiStreamChunk, tonic::Status>(first.into());
            while let Some(chunk) = rx.recv().await {
                yield Ok(chunk.into());
            }
            // The turn is over. `Done` is appended by the SDK so no plugin has
            // to remember to send it, and an error that arrives mid-stream is
            // delivered as the stream's own error variant — the daemon's AI loop
            // reads that and stops; a `Status` here would be dropped.
            match task.await {
                Ok(Ok(())) => yield Ok(AiChunk::Done.into()),
                Ok(Err(e)) => yield Ok(ai_error_chunk(ToolError::from(e))),
                Err(e) => yield Ok(ai_error_chunk(ToolError::Internal(format!(
                    "ai_complete panicked: {e}"
                )))),
            }
        };
        Ok(tonic::Response::new(Box::pin(out)))
    }

    async fn ai_get_models(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::PluginAiModelsResponse>, tonic::Status> {
        let (models, default) = catch("ai_models", self.plugin.ai_models()).await?;
        Ok(tonic::Response::new(proto::PluginAiModelsResponse {
            models: models.into_iter().map(Into::into).collect(),
            default_model: default,
        }))
    }

    // ── Actions ──

    async fn execute_action(
        &self,
        request: tonic::Request<proto::PluginExecuteActionRequest>,
    ) -> Result<tonic::Response<proto::PluginExecuteActionResponse>, tonic::Status> {
        let req = request.into_inner();
        let resp = match caught_tool(
            "execute_action",
            self.plugin
                .execute_action(&self.ctx, &req.action_type, &req.params_json),
        )
        .await
        {
            Ok(result) => proto::PluginExecuteActionResponse {
                success: true,
                result,
                error: String::new(),
                error_detail: None,
            },
            Err(e) => proto::PluginExecuteActionResponse {
                success: false,
                result: String::new(),
                error: e.wire_string(),
                error_detail: Some(e.to_plugin_error()),
            },
        };
        Ok(tonic::Response::new(resp))
    }

    async fn get_plugin_action_types(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::PluginActionTypesResponse>, tonic::Status> {
        let types = catch("action_types", self.plugin.action_types()).await?;
        Ok(tonic::Response::new(proto::PluginActionTypesResponse {
            types,
        }))
    }

    // ── Triggers ──

    async fn get_plugin_trigger_types(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::PluginTriggerTypesResponse>, tonic::Status> {
        let types = catch("trigger_types", self.plugin.trigger_types()).await?;
        Ok(tonic::Response::new(proto::PluginTriggerTypesResponse {
            types,
        }))
    }

    // ── UI ──

    async fn get_ui_contributions(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::PluginUiContributionsResponse>, tonic::Status> {
        let contributions = catch("ui_contributions", self.plugin.ui_contributions()).await?;
        Ok(tonic::Response::new(proto::PluginUiContributionsResponse {
            contributions,
        }))
    }

    async fn call_from_ui(
        &self,
        request: tonic::Request<proto::PluginUiCallRequest>,
    ) -> Result<tonic::Response<proto::PluginUiCallResponse>, tonic::Status> {
        let req = request.into_inner();
        let resp = match caught_tool(
            "handle_ui_call",
            self.plugin
                .handle_ui_call(&self.ctx, &req.method, &req.params_json),
        )
        .await
        {
            Ok(result_json) => proto::PluginUiCallResponse {
                result_json,
                error: String::new(),
                error_detail: None,
            },
            Err(e) => proto::PluginUiCallResponse {
                result_json: String::new(),
                error: e.wire_string(),
                error_detail: Some(e.to_plugin_error()),
            },
        };
        Ok(tonic::Response::new(resp))
    }

    // ── Lifecycle ──

    async fn on_config_changed(
        &self,
        request: tonic::Request<proto::PluginConfigChangedMsg>,
    ) -> Result<tonic::Response<proto::Empty>, tonic::Status> {
        let config_json = request.into_inner().config_json;
        catch(
            "on_config_changed",
            self.plugin.on_config_changed(&self.ctx, &config_json),
        )
        .await?;
        Ok(tonic::Response::new(proto::Empty {}))
    }

    async fn on_active_triggers(
        &self,
        request: tonic::Request<proto::PluginActiveTriggersMsg>,
    ) -> Result<tonic::Response<proto::Empty>, tonic::Status> {
        let types = request.into_inner().trigger_types;
        // Applied to the context BEFORE the hook runs. `ActiveTriggers` was a
        // type nothing ever wrote to — a plugin that asked "is anyone listening"
        // was always told no. Now the hook and `ctx.active_triggers()` cannot
        // disagree, because the hook cannot observe the older value.
        self.ctx.active_triggers().set(types.clone());
        catch(
            "on_active_triggers",
            self.plugin.on_active_triggers(&self.ctx, types),
        )
        .await?;
        Ok(tonic::Response::new(proto::Empty {}))
    }

    async fn on_language_changed(
        &self,
        request: tonic::Request<proto::LanguageChangedMsg>,
    ) -> Result<tonic::Response<proto::Empty>, tonic::Status> {
        let language = request.into_inner().language;
        self.ctx.set_language(language.clone());
        catch(
            "on_language_changed",
            self.plugin.on_language_changed(&self.ctx, &language),
        )
        .await?;
        Ok(tonic::Response::new(proto::Empty {}))
    }

    async fn shutdown(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::Empty>, tonic::Status> {
        info!("Shutdown requested by daemon");
        // Ask the server to stop and reply immediately. Graceful shutdown
        // drains this request first, so the daemon gets its response; `run_with`
        // then calls `on_shutdown()` once the server is down. (The old code slept
        // 100 ms in a detached task and called `process::exit(0)`, which killed
        // the process mid-`on_shutdown` whenever cleanup took longer than that.)
        self.shutdown.trigger();
        Ok(tonic::Response::new(proto::Empty {}))
    }

    async fn health_check(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::PluginHealthResponse>, tonic::Status> {
        // A panic here answers "not healthy", which is true and actionable —
        // the daemon restarts the plugin. A `Status` would be read as the probe
        // failing, which it also treats as dead, but without the sentence.
        let (healthy, status) = match crate::panics::catch("health_check", self.plugin.health_check())
            .await
        {
            Ok(answer) => answer,
            Err(panicked) => (false, panicked.to_string()),
        };
        Ok(tonic::Response::new(proto::PluginHealthResponse {
            healthy,
            status,
        }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::capability::{AiRequest, NoConfig};

    fn argv(items: &[&str]) -> Vec<String> {
        items.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn keeps_daemon_flags_in_both_spellings() {
        let out = daemon_args(argv(&[
            "plugin",
            "--daemon-addr",
            "127.0.0.1:32000",
            "--plugin-id=dice",
            "--auth-token",
            "secret",
            "--capabilities",
            "tools,triggers",
        ]));
        assert_eq!(
            out,
            argv(&[
                "plugin",
                "--daemon-addr",
                "127.0.0.1:32000",
                "--plugin-id=dice",
                "--auth-token",
                "secret",
                "--capabilities",
                "tools,triggers",
            ])
        );
    }

    #[test]
    fn drops_flags_the_plugin_owns() {
        // A plugin's own CLI must not make the SDK's parser abort the process.
        let out = daemon_args(argv(&[
            "plugin",
            "--verbose",
            "serve",
            "--daemon-addr",
            "127.0.0.1:32000",
            "--config=/tmp/x.toml",
            "--plugin-id",
            "dice",
        ]));
        assert_eq!(
            out,
            argv(&[
                "plugin",
                "--daemon-addr",
                "127.0.0.1:32000",
                "--plugin-id",
                "dice",
            ])
        );
        Args::parse_from(out);
    }

    #[test]
    fn parses_a_daemon_spawn_line() {
        let args = Args::parse_from(daemon_args(argv(&[
            "plugin",
            "--daemon-addr",
            "127.0.0.1:32000",
            "--plugin-id",
            "dice",
            "--auth-token",
            "tok",
            "--capabilities",
            "tools,triggers,actions",
            "--my-own-flag",
        ])));
        assert_eq!(args.daemon_addr, "127.0.0.1:32000");
        assert_eq!(args.plugin_id, "dice");
        assert_eq!(args.auth_token, "tok");
        assert_eq!(args.capabilities, vec!["tools", "triggers", "actions"]);
    }

    /// 5.4: the capability list is DATA FROM THE MANIFEST, delivered by the
    /// daemon. It is never inferred from which trait methods happen to return
    /// something, which is what 0.5's `discover_capabilities` did.
    #[test]
    fn the_daemons_capability_list_wins_over_the_binarys() {
        // The daemon's channel is `ASTRA_PLUGIN_CAPABILITIES`; an explicit
        // `--capabilities` on argv (a harness, a `dev` sideload) outranks it.
        assert_eq!(
            resolve_capabilities(
                argv(&["tools", "triggers"]),
                Some(argv(&["stt"])),
                &[String::from("actions")]
            ),
            argv(&["tools", "triggers"])
        );
        assert_eq!(
            resolve_capabilities(
                vec![],
                Some(argv(&["tools", "triggers"])),
                &[String::from("stt")]
            ),
            argv(&["tools", "triggers"])
        );
    }

    /// `Some(empty)` and `None` are different statements.
    ///
    /// The daemon always sets `ASTRA_PLUGIN_CAPABILITIES`, empty included:
    /// empty is "this manifest declares none", and the variable being ABSENT is
    /// "the daemon predates §5.4". Collapsing the two would let a plugin whose
    /// manifest declares nothing quietly register with whatever it was built
    /// with — overriding the file the user actually consented to.
    #[test]
    fn a_manifest_that_declares_nothing_is_not_the_same_as_an_old_daemon() {
        assert!(
            resolve_capabilities(vec![], Some(vec![String::new()]), &[String::from("tools")])
                .is_empty(),
            "an empty statement from the daemon is still the daemon's statement",
        );
        assert_eq!(
            resolve_capabilities(vec![], None, &[String::from("tools")]),
            argv(&["tools"]),
            "no statement at all is what falls back to the binary's declaration",
        );
    }

    #[test]
    fn an_older_daemon_that_states_nothing_falls_back_to_the_binarys_declaration() {
        assert_eq!(
            resolve_capabilities(vec![], None, &[String::from("tools")]),
            argv(&["tools"])
        );
        // Whitespace and empty entries from `ASTRA_PLUGIN_CAPABILITIES=tools,,`
        // are not capabilities.
        assert_eq!(
            resolve_capabilities(vec![], Some(argv(&["tools", " ", ""])), &[]),
            argv(&["tools"])
        );
        assert!(resolve_capabilities(vec![], None, &[]).is_empty());
    }

    /// The parse of the daemon's variable, including the two cases that are not
    /// a list: unset, and set to the empty string.
    #[test]
    fn the_capability_variable_parses_the_way_the_daemon_writes_it() {
        // `std::env::set_var` is process-global; this test owns the variable
        // and restores it, and no other test in this module reads it.
        let previous = std::env::var(CAPABILITIES_ENV).ok();

        unsafe { std::env::remove_var(CAPABILITIES_ENV) };
        assert_eq!(capabilities_from_env(), None, "unset is `None`, not empty");

        unsafe { std::env::set_var(CAPABILITIES_ENV, "") };
        assert_eq!(
            resolve_capabilities(vec![], capabilities_from_env(), &[String::from("tools")]),
            Vec::<String>::new(),
            "set-but-empty is the daemon saying this manifest declares none",
        );

        unsafe { std::env::set_var(CAPABILITIES_ENV, "tools,triggers") };
        assert_eq!(
            resolve_capabilities(vec![], capabilities_from_env(), &[]),
            argv(&["tools", "triggers"]),
        );

        match previous {
            Some(v) => unsafe { std::env::set_var(CAPABILITIES_ENV, v) },
            None => unsafe { std::env::remove_var(CAPABILITIES_ENV) },
        }
    }

    /// 5.5's seam: `astra-plugin check` has to be able to ask a binary what it
    /// declares without a daemon, a port or a `--plugin-id`. It answers before
    /// argv is even parsed, so it works on a plugin with its own required CLI.
    #[tokio::test]
    async fn print_capabilities_answers_with_no_daemon_and_no_other_flags() {
        let config = RunConfig {
            argv: Some(argv(&["plugin", PRINT_CAPABILITIES_FLAG])),
            capabilities: argv(&["tools", "triggers"]),
            init_tracing: false,
            ..RunConfig::default()
        };
        run_with(BarePlugin, config)
            .await
            .expect("--print-capabilities must not need a daemon");
    }

    /// A plugin that overrides nothing — every `PluginCapability` method has a
    /// default, so this serves the whole capability surface.
    struct BarePlugin;
    impl PluginCapability for BarePlugin {
        type Config = NoConfig;
    }

    /// The context a service test runs against: a host that answers everything
    /// with `Ok` and records nothing. (Task 5.6 turns this into the public
    /// `RecordingHost`; the shape is already right because `Host` is a trait.)
    struct SilentHost;

    #[async_trait::async_trait]
    impl Host for SilentHost {
        fn plugin_id(&self) -> &str {
            "test"
        }
        async fn fire_trigger(&self, _: &str, _: &str) -> Result<()> {
            Ok(())
        }
        async fn log(&self, _: &str, _: &str) -> Result<()> {
            Ok(())
        }
        async fn get_config(&self) -> Result<String> {
            Ok("{}".into())
        }
        async fn get_daemon_info(&self) -> Result<proto::PluginDaemonInfoResponse> {
            Ok(Default::default())
        }
        async fn set_variable(&self, _: &str, _: &str, _: &str) -> Result<()> {
            Ok(())
        }
        async fn push_to_ui(&self, _: &str, _: &str) -> Result<()> {
            Ok(())
        }
        async fn send_chat_message(
            &self,
            _: &str,
            _: &str,
            _: bool,
        ) -> Result<crate::context::ChatStream> {
            Ok(Box::pin(tokio_stream::empty()))
        }
        async fn set_theme_contribution(&self, _: proto::PluginThemeContribution) -> Result<()> {
            Ok(())
        }
    }

    fn test_ctx() -> PluginContext {
        PluginContext::new("test", Arc::new(SilentHost))
    }

    /// Bind a capability server guarded exactly as `run_with` binds it.
    async fn serve_guarded(token: &str, mode: CapabilityAuth) -> String {
        serve_plugin(BarePlugin, token, mode).await
    }

    async fn serve_plugin<P: PluginCapability>(
        plugin: P,
        token: &str,
        mode: CapabilityAuth,
    ) -> String {
        let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
            .await
            .unwrap();
        let addr = listener.local_addr().unwrap();
        let (tx, rx) = oneshot::channel::<()>();
        let svc = CapabilityServiceImpl {
            plugin: Arc::new(plugin),
            ctx: test_ctx(),
            shutdown: ShutdownTrigger::new(tx),
        };
        let guard = CapabilityInterceptor::new(token, mode);
        tokio::spawn(
            Server::builder()
                .add_service(PluginCapabilityServiceServer::with_interceptor(svc, guard))
                .serve_with_incoming_shutdown(
                    tokio_stream::wrappers::TcpListenerStream::new(listener),
                    async move {
                        let _ = rx.await;
                    },
                ),
        );
        format!("http://{addr}")
    }

    type Client = proto::plugin_capability_service_client::PluginCapabilityServiceClient<
        tonic::transport::Channel,
    >;

    async fn connect(addr: &str) -> Client {
        Client::connect(addr.to_string()).await.unwrap()
    }

    /// `ListTools` against `addr`, optionally presenting `token`.
    async fn list_tools(addr: &str, token: Option<&str>) -> Result<(), tonic::Code> {
        let mut client = connect(addr).await;
        let mut req = tonic::Request::new(proto::Empty {});
        if let Some(token) = token {
            req.metadata_mut()
                .insert("x-plugin-token", token.parse().unwrap());
        }
        client.list_tools(req).await.map(|_| ()).map_err(|e| e.code())
    }

    #[tokio::test]
    async fn capability_server_rejects_a_wrong_token_over_the_wire() {
        // The unit tests in `auth` cover the decision; this covers the wiring —
        // that tonic really runs the interceptor for this service, so a local
        // process that is not the daemon cannot reach the plugin's tools.
        let addr = serve_guarded("s3cret", CapabilityAuth::Warn).await;
        assert_eq!(list_tools(&addr, Some("s3cret")).await, Ok(()));
        assert_eq!(list_tools(&addr, None).await, Ok(())); // accept-and-warn
        assert_eq!(
            list_tools(&addr, Some("wrong")).await,
            Err(tonic::Code::Unauthenticated)
        );
    }

    #[tokio::test]
    async fn capability_server_can_require_the_token() {
        let addr = serve_guarded("s3cret", CapabilityAuth::Require).await;
        assert_eq!(
            list_tools(&addr, None).await,
            Err(tonic::Code::Unauthenticated)
        );
        assert_eq!(list_tools(&addr, Some("s3cret")).await, Ok(()));
    }

    #[tokio::test]
    async fn capability_server_without_a_spawn_token_still_serves() {
        // A plugin run standalone shares no secret with anyone; failing closed
        // there would make it unrunnable rather than safe.
        let addr = serve_guarded("", CapabilityAuth::Require).await;
        assert_eq!(list_tools(&addr, None).await, Ok(()));
    }

    /// The forward-compatibility contract: an unimplemented hook answers
    /// UNIMPLEMENTED, which the daemon reads as "absent" — not INTERNAL, which
    /// it reads as "broken". The streaming hooks are the interesting ones,
    /// because a status can only be set before the first chunk.
    #[tokio::test]
    async fn an_unimplemented_hook_answers_unimplemented_even_when_it_streams() {
        let addr = serve_guarded("", CapabilityAuth::Off).await;
        let mut c = connect(&addr).await;

        let err = c
            .tts_synthesize(proto::PluginTtsSynthesizeRequest::default())
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::Unimplemented, "{err}");

        let err = c
            .tts_synthesize_stream(proto::PluginTtsSynthesizeRequest::default())
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::Unimplemented, "{err}");

        let err = c
            .ai_complete(proto::PluginAiCompleteRequest::default())
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::Unimplemented, "{err}");

        for err in [
            c.stt_load(proto::SttLoadRequest::default()).await.unwrap_err(),
            c.stt_unload(proto::Empty {}).await.unwrap_err(),
            c.stt_get_load_state(proto::Empty {}).await.unwrap_err(),
            c.tts_activate(proto::PluginTtsActivateRequest::default())
                .await
                .unwrap_err(),
        ] {
            assert_eq!(err.code(), tonic::Code::Unimplemented, "{err}");
        }
    }

    /// 5.2, over a real socket: a per-call failure is DATA. It comes back as a
    /// successful RPC with `success = false` and a coded message, because the
    /// AI loop has to read it. A `Status` here would be a transport failure and
    /// the model would be told nothing.
    #[tokio::test]
    async fn a_tool_failure_is_in_band_and_carries_its_code() {
        struct NeedsAKey;
        #[async_trait::async_trait]
        impl PluginCapability for NeedsAKey {
            type Config = NoConfig;
            async fn call_tool(
                &self,
                _ctx: &PluginContext,
                _name: &str,
                _args: &str,
            ) -> Result<String, ToolError> {
                Err(ToolError::not_configured_with(
                    "api_key",
                    "OpenAI API key is not set",
                ))
            }
        }

        let addr = serve_plugin(NeedsAKey, "", CapabilityAuth::Off).await;
        let mut c = connect(&addr).await;
        let resp = c
            .call_tool(proto::PluginCallToolRequest {
                tool_name: "ask".into(),
                arguments_json: "{}".into(),
            })
            .await
            .expect("a failed tool call is still a successful RPC")
            .into_inner();
        assert!(!resp.success);
        assert!(resp.error.starts_with("NOT_CONFIGURED: "), "{}", resp.error);
        assert!(resp.error.contains("api_key"), "{}", resp.error);
    }

    /// 5.4: `OnActiveTriggers` has to reach the CONTEXT, not just the hook.
    /// Before this, `ActiveTriggers` was a type with no writer — every
    /// `contains()` answered false and plugins fired triggers nobody wanted.
    #[tokio::test]
    async fn active_triggers_reach_the_context_before_the_hook_runs() {
        use std::sync::atomic::{AtomicBool, Ordering};
        static SAW_IT: AtomicBool = AtomicBool::new(false);

        struct Watcher;
        #[async_trait::async_trait]
        impl PluginCapability for Watcher {
            type Config = NoConfig;
            async fn on_active_triggers(&self, ctx: &PluginContext, _types: Vec<String>) {
                // The hook cannot observe the older value.
                SAW_IT.store(ctx.active_triggers().contains("on_roll_value"), Ordering::SeqCst);
            }
        }

        let addr = serve_plugin(Watcher, "", CapabilityAuth::Off).await;
        connect(&addr)
            .await
            .on_active_triggers(proto::PluginActiveTriggersMsg {
                trigger_types: vec!["on_roll_value".into()],
            })
            .await
            .unwrap();
        assert!(SAW_IT.load(Ordering::SeqCst));
    }

    /// A Rust plugin can serve AI completions and stream TTS — 5.4's acceptance,
    /// end to end over a socket.
    #[tokio::test]
    async fn a_plugin_can_serve_ai_completions_and_stream_tts() {
        struct Provider;
        #[async_trait::async_trait]
        impl PluginCapability for Provider {
            type Config = NoConfig;

            async fn ai_complete(
                &self,
                _ctx: &PluginContext,
                req: AiRequest,
                chunks: tokio::sync::mpsc::Sender<AiChunk>,
            ) -> Result<()> {
                // The reasoning knobs were on the wire and reachable by no SDK
                // before 0.6; a provider that cannot see them cannot honour the
                // user's setting.
                if req.show_reasoning {
                    chunks.send(AiChunk::thinking("hmm")).await?;
                }
                chunks.send(AiChunk::text("hello")).await?;
                chunks.send(AiChunk::text(req.reasoning_effort)).await?;
                Ok(())
            }

            async fn tts_synthesize_stream(
                &self,
                _ctx: &PluginContext,
                req: TtsRequest,
                chunks: tokio::sync::mpsc::Sender<AudioChunk>,
            ) -> Result<()> {
                for (i, _word) in req.text.split_whitespace().enumerate() {
                    chunks.send(AudioChunk::new(vec![i as u8], 24_000)).await?;
                }
                chunks.send(AudioChunk::new(vec![], 24_000).last()).await?;
                Ok(())
            }
        }

        use tokio_stream::StreamExt;
        let addr = serve_plugin(Provider, "", CapabilityAuth::Off).await;
        let mut c = connect(&addr).await;

        let mut stream = c
            .ai_complete(proto::PluginAiCompleteRequest {
                reasoning_effort: "high".into(),
                show_reasoning: true,
                ..Default::default()
            })
            .await
            .unwrap()
            .into_inner();
        let mut got = Vec::new();
        while let Some(chunk) = stream.next().await {
            got.push(chunk.unwrap().content.unwrap());
        }
        use proto::plugin_ai_stream_chunk::Content;
        assert!(matches!(&got[0], Content::ThinkingDelta(t) if t == "hmm"));
        assert!(matches!(&got[1], Content::TextDelta(t) if t == "hello"));
        assert!(matches!(&got[2], Content::TextDelta(t) if t == "high"));
        // `Done` is appended by the SDK, so no plugin has to remember it.
        assert!(matches!(got[3], Content::Done(true)));

        let mut stream = c
            .tts_synthesize_stream(proto::PluginTtsSynthesizeRequest {
                text: "one two three".into(),
                ..Default::default()
            })
            .await
            .unwrap()
            .into_inner();
        let mut chunks = Vec::new();
        while let Some(chunk) = stream.next().await {
            chunks.push(chunk.unwrap());
        }
        assert_eq!(chunks.len(), 4);
        assert!(chunks.last().unwrap().is_last);
    }

    /// The default streaming TTS is "synthesize the lot, send one chunk", so a
    /// provider that only implements `tts_synthesize` streams for free.
    #[tokio::test]
    async fn a_non_streaming_tts_provider_still_answers_the_streaming_hook() {
        use crate::capability::AudioData;

        struct OneShot;
        #[async_trait::async_trait]
        impl PluginCapability for OneShot {
            type Config = NoConfig;
            async fn tts_synthesize(
                &self,
                _ctx: &PluginContext,
                _req: TtsRequest,
            ) -> Result<AudioData> {
                Ok(AudioData {
                    data: vec![1, 2, 3],
                    format: "wav".into(),
                    sample_rate: 24_000,
                    duration_ms: 10,
                })
            }
        }

        use tokio_stream::StreamExt;
        let addr = serve_plugin(OneShot, "", CapabilityAuth::Off).await;
        let mut stream = connect(&addr)
            .await
            .tts_synthesize_stream(proto::PluginTtsSynthesizeRequest::default())
            .await
            .unwrap()
            .into_inner();
        let chunk = stream.next().await.unwrap().unwrap();
        assert_eq!(chunk.data, vec![1, 2, 3]);
        assert!(chunk.is_last);
        assert!(stream.next().await.is_none());
    }

    /// 5.3: config arrives typed, and config that does not fit the type does not
    /// silently replace the config that does.
    #[tokio::test]
    async fn config_arrives_typed_and_a_bad_payload_keeps_the_old_one() {
        use std::sync::atomic::{AtomicU32, Ordering};
        static SIDES: AtomicU32 = AtomicU32::new(6);

        #[derive(serde::Deserialize)]
        struct Cfg {
            sides: u32,
        }

        struct Typed;
        #[async_trait::async_trait]
        impl PluginCapability for Typed {
            type Config = Cfg;
            async fn on_config(&self, _ctx: &PluginContext, cfg: Cfg) {
                SIDES.store(cfg.sides, Ordering::SeqCst);
            }
        }

        let addr = serve_plugin(Typed, "", CapabilityAuth::Off).await;
        let mut c = connect(&addr).await;

        c.on_config_changed(proto::PluginConfigChangedMsg {
            config_json: r#"{"sides":20}"#.into(),
        })
        .await
        .unwrap();
        assert_eq!(SIDES.load(Ordering::SeqCst), 20);

        // A user (or a daemon migration) writing the wrong shape must not make
        // the plugin run on a half-parsed config, and must not kill it either.
        c.on_config_changed(proto::PluginConfigChangedMsg {
            config_json: r#"{"sides":"twenty"}"#.into(),
        })
        .await
        .unwrap();
        assert_eq!(SIDES.load(Ordering::SeqCst), 20, "old config kept");
    }
}
