#!/usr/bin/env python3
"""`plugin_pb2.py` and `plugin_pb2_grpc.py` are what Python actually loads.

    python3 tools/check-python-stubs.py

The protocol is this repository's best-guarded fact — `proto-slice --check` in
Astra, `tools/check-proto.sh` (byte-identity across four copies, and it refuses
a stray `plugin.proto` anywhere in the tree), `gen-proto-lock.sh --check`, the
`proto (upstream drift)` job, and C3 pinning the TypeScript descriptor's
provenance separately.

**It stopped one hop short of the thing Python imports.** The two generated
modules under `astra_plugin_sdk/proto/` are committed artifacts, regenerated by
hand, and until this file existed they were named by exactly one thing in the
whole tooling surface: `tools/sync-proto.sh:19` — *a comment saying they need
regenerating*. Nothing regenerated them and nothing compared them.

What that cost is the part worth recording. `plugin_pb2.py` was stale from Wave
4 — the wave whose entire purpose was surfacing `PluginChatChunk.conversation_id`
in all three SDKs. The committed descriptor carried `text`, `done`, `error`,
`message_id`, `error_detail` and stopped; there was no field 6. So the Python
SDK's own docstring told authors to read a field that did not exist on the
class, and 141 passing pytest tests could not say so — because the tests
*import* the artifact rather than assert about it:

    A test suite agrees with a stale artifact most confidently when the
    artifact is a DATA FILE THE TESTS IMPORT rather than something they
    assert about.

This is the assertion. It regenerates into a temporary directory and compares,
byte for byte, the way `docgen --check` and `parity/gen.py --check` already do
for their artifacts.

WHAT IT ALSO CATCHES, which is not obvious

`astra_plugin_sdk/proto/__init__.py` documents a TWO-step recipe: protoc, then a
`sed` that rewrites protoc's top-level `import plugin_pb2` into a package-relative
one. The recipe used to stop after protoc, and following it exactly produced a
package that could not import itself. Applying the same rewrite here means a
regeneration that forgets the second step is a red build rather than eight
broken CI jobs.

THE TOOLCHAIN IS PART OF THE ARTIFACT

protoc's output is deterministic for a given version and not across versions: a
newer grpcio-tools rewrites unrelated lines and raises the runtime floor the
stub asserts at import. So this check reads the version the committed stub
records in its own `GRPC_GENERATED_VERSION` and refuses to compare against a
different one. That refusal is reported as a TOOLCHAIN MISMATCH, in as many
words, and never as protocol drift — the two have completely different fixes
and only one of them is urgent.

Exit 0 all current · 1 something is wrong · 2 this check could not run.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROTO_DIR = ROOT / "astra-plugin-sdk-python" / "astra_plugin_sdk" / "proto"
PROTO = PROTO_DIR / "plugin.proto"

#: The generated artifacts, and the only two files this check compares.
ARTIFACTS = ("plugin_pb2.py", "plugin_pb2_grpc.py")

#: Everything else that may live beside them, and why it is not compared here.
#:
#: An exemption list rather than a silence, because the rule is "every
#: generated artifact in this directory is regenerated and compared" and a new
#: one must arrive as a one-line answer to *does this need it, and why not?*
#: rather than as an absence nobody notices. That is exactly how the two files
#: above came to be unguarded for a fortnight.
EXEMPT = {
    "__init__.py": "hand-written; it holds the regeneration recipe this check runs",
    "README.md": "hand-written; it explains why the proto copy exists",
    "plugin.proto": "the INPUT, and the most-guarded file in the tree — "
                    "tools/check-proto.sh holds it byte-identical to proto/plugin.proto",
    "__pycache__": "not tracked; C10 in the couplings job refuses committed build output",
}

#: protoc's own import line, and the package-relative one the committed stub
#: must carry. Both spellings are asserted: if protoc stops emitting the first,
#: this rewrite silently stops applying and the comparison starts measuring
#: something else.
PROTOC_IMPORT = "import plugin_pb2 as plugin__pb2"
PACKAGE_IMPORT = "from . import plugin_pb2 as plugin__pb2"

#: A floor on each regenerated file. Not the real size — a floor, so that a
#: protoc run which produces a stub for an empty or truncated proto fails as a
#: broken run rather than being compared successfully against an equally broken
#: committed file. The real files are 135 KB and 291 KB.
MIN_ARTIFACT_BYTES = 20_000


def die(message: str, code: int = 1) -> None:
    print(f"check-python-stubs: {message}", file=sys.stderr)
    raise SystemExit(code)


def required_toolchain() -> str:
    """The grpcio-tools version the committed stub says produced it."""
    text = (PROTO_DIR / "plugin_pb2_grpc.py").read_text(encoding="utf-8")
    m = re.search(r"^GRPC_GENERATED_VERSION = '([^']+)'", text, re.M)
    if not m:
        die(
            "the committed plugin_pb2_grpc.py has no `GRPC_GENERATED_VERSION = '…'` line.\n"
            "  That constant is the artifact's own record of what produced it, and this\n"
            "  check has nothing to pin the comparison to without it. This is a FAILURE\n"
            "  and not a skip: the anchor moved rather than being absent.",
            2,
        )
    return m.group(1)


def installed_toolchain() -> str:
    try:
        import grpc_tools  # noqa: F401
    except ImportError:
        die(
            "grpcio-tools is not importable, so nothing can be regenerated.\n"
            "  It is a RUNTIME dependency of astra-plugin-sdk (pyproject.toml), so this is\n"
            "  usually a missing install rather than a decision:\n"
            f"    python -m pip install 'grpcio-tools=={required_toolchain()}'",
            2,
        )
    from importlib import metadata

    try:
        return metadata.version("grpcio-tools")
    except metadata.PackageNotFoundError:  # pragma: no cover — vendored oddity
        die("grpcio-tools imports but has no distribution metadata; cannot pin a version", 2)
        raise


def regenerate(into: Path) -> None:
    """protoc, then the `sed` step `proto/__init__.py` documents. Both."""
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "grpc_tools.protoc",
            "-I",
            str(PROTO_DIR),
            f"--python_out={into}",
            f"--grpc_python_out={into}",
            str(PROTO),
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        die(
            "grpc_tools.protoc failed, so there is nothing to compare against:\n"
            + "\n".join("    " + l for l in (result.stderr or result.stdout).splitlines()),
            2,
        )

    grpc_stub = into / "plugin_pb2_grpc.py"
    text = grpc_stub.read_text(encoding="utf-8")
    hits = len(re.findall(rf"^{re.escape(PROTOC_IMPORT)}$", text, re.M))
    if hits != 1:
        die(
            f"the freshly generated plugin_pb2_grpc.py has {hits} occurrences of\n"
            f"    {PROTOC_IMPORT}\n"
            "  and this check rewrites exactly one, the way astra_plugin_sdk/proto/__init__.py\n"
            "  documents. protoc's output shape changed, so the comparison below would be\n"
            "  measuring something other than the thing under test. This is the scan\n"
            "  breaking, not the artifact drifting.",
            2,
        )
    grpc_stub.write_text(
        re.sub(rf"^{re.escape(PROTOC_IMPORT)}$", PACKAGE_IMPORT, text, count=1, flags=re.M),
        encoding="utf-8",
    )


def main() -> int:
    if not PROTO.is_file():
        die(f"{PROTO} is missing; tools/check-proto.sh is the check that owns it", 2)

    # ── the exemption list, first: a new artifact must be a visible blank ──
    present = sorted(p.name for p in PROTO_DIR.iterdir())
    unclassified = [n for n in present if n not in ARTIFACTS and n not in EXEMPT]
    if unclassified:
        die(
            f"{PROTO_DIR.relative_to(ROOT)} holds file(s) this check has never heard of: "
            + ", ".join(unclassified)
            + "\n  Every generated artifact in that directory is regenerated and compared here.\n"
            "  Add it to ARTIFACTS, or answer the question in EXEMPT: does this need\n"
            "  regenerating, and why not? An absence nobody notices is how plugin_pb2.py\n"
            "  came to be stale for a fortnight while 141 tests passed over it."
        )
    missing = [n for n in ARTIFACTS if not (PROTO_DIR / n).is_file()]
    if missing:
        die(f"the committed artifact(s) {', '.join(missing)} are not there at all")

    # ── the toolchain, second, so drift can never be reported for it ──
    want = required_toolchain()
    have = installed_toolchain()
    if have != want:
        die(
            f"TOOLCHAIN MISMATCH — grpcio-tools {have} is installed, the committed stubs\n"
            f"  were generated with {want}. This is NOT protocol drift and nothing below ran.\n"
            "\n"
            "  protoc's output is deterministic for one version and not across versions: a\n"
            "  newer one rewrites unrelated lines and raises the runtime floor the stub\n"
            "  asserts at import against the installed grpcio. Moving that floor is a\n"
            "  decision about this package's minimum runtime, not a side effect of syncing\n"
            "  a proto, so it belongs in its own commit with its own reason\n"
            "  (astra_plugin_sdk/proto/__init__.py says so at length).\n"
            "\n"
            f"  To run this check:   python -m pip install 'grpcio-tools=={want}'\n"
            "  To move the pin:     regenerate deliberately, and this check then wants the\n"
            "                       new version because the stub records it itself.",
            2,
        )

    # ── the comparison ──
    tmp = Path(tempfile.mkdtemp(prefix="astra-pb2-"))
    try:
        regenerate(tmp)
        drifted: list[str] = []
        compared = 0
        for name in ARTIFACTS:
            fresh = tmp / name
            if not fresh.is_file():
                die(
                    f"protoc produced no {name}. Nothing was compared for it, and a check "
                    "that compares nothing passes for the wrong reason.",
                    2,
                )
            fresh_bytes = fresh.read_bytes()
            if len(fresh_bytes) < MIN_ARTIFACT_BYTES:
                die(
                    f"the freshly generated {name} is {len(fresh_bytes)} bytes, under the "
                    f"{MIN_ARTIFACT_BYTES}-byte floor.\n"
                    "  That is a protoc run over an empty or truncated proto, not a shrunken\n"
                    "  protocol — and comparing it against an equally broken committed file\n"
                    "  would pass. The scan broke, not the rule.",
                    2,
                )
            committed = (PROTO_DIR / name).read_bytes()
            compared += 1
            if committed == fresh_bytes:
                print(f"ok    {name} is what plugin.proto generates ({len(committed)} bytes)")
            else:
                drifted.append(name)
                print(f"FAIL  {name} is NOT what plugin.proto generates", file=sys.stderr)

        if compared < len(ARTIFACTS):  # pragma: no cover — belt to the braces above
            die(f"only {compared} of {len(ARTIFACTS)} artifacts were compared")

        if drifted:
            die(
                f"{len(drifted)} committed artifact(s) do not match the protocol beside them: "
                + ", ".join(drifted)
                + "\n"
                "\n  This is what Python imports. A stale plugin_pb2.py means a field the\n"
                "  protocol carries does not exist on the class, and every test that imports\n"
                "  the module agrees with it.\n"
                "\n  Regenerate, from astra-plugin-sdk-python/ — BOTH steps, see\n"
                "  astra_plugin_sdk/proto/__init__.py:\n"
                f"    python -m pip install 'grpcio-tools=={want}'\n"
                "    python -m grpc_tools.protoc -I astra_plugin_sdk/proto \\\n"
                "      --python_out=astra_plugin_sdk/proto --grpc_python_out=astra_plugin_sdk/proto \\\n"
                "      astra_plugin_sdk/proto/plugin.proto\n"
                f"    sed -i 's|^{PROTOC_IMPORT}$|{PACKAGE_IMPORT}|' \\\n"
                "      astra_plugin_sdk/proto/plugin_pb2_grpc.py"
            )
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print(
        f"check-python-stubs: {compared} artifact(s) regenerated with grpcio-tools {have} "
        f"and byte-identical to what is committed."
    )
    print(
        f"check-python-stubs: NOT CHECKED — whether plugin.proto is itself current. That is "
        f"tools/check-proto.sh\ncheck-python-stubs:              and the `proto (upstream "
        f"drift)` job; this one starts where they stop."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
