#!/usr/bin/env bash
#
# sync-proto.sh — copy the canonical protocol into the two places packaging
# cannot reach out of, and re-pin proto/PROTO_VERSION.
#
# There is exactly one protocol file in this repo: proto/plugin.proto. It is
# generated in the Astra repo by astra-rs/tools/proto-slice and copied here; do
# not hand-edit it, and do not hand-edit the vendored copies this script writes.
#
# Why copies exist at all — packaging, and nothing else:
#
#   astra-plugin-sdk/proto/plugin.proto
#       `cargo package` refuses to include a file outside the crate root, so
#       build.rs cannot compile ../proto/plugin.proto from a published .crate.
#
#   astra-plugin-sdk-python/astra_plugin_sdk/proto/plugin.proto
#       setuptools has the same constraint: an sdist/wheel carries package data
#       from inside the package directory only. This copy is the input for
#       regenerating plugin_pb2.py / plugin_pb2_grpc.py (see its __init__.py).
#
# Two consumers vendor nothing:
#
#   astra-plugin-sdk-ts   generates src/generated/descriptor.json from the
#                         canonical proto at build time (tools/gen-descriptor.mjs).
#   astra-plugin-cli      ships no protocol file at all.
#
# The copies are byte-identical to the canonical file — same sha256, the one
# pinned in proto/PROTO_VERSION. That is the whole invariant, and it is what
# tools/check-proto.sh (and CI) enforces.
#
# Usage: tools/sync-proto.sh          # write the copies and PROTO_VERSION
#
set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

CANONICAL_REL="proto/plugin.proto"
VERSION_REL="proto/PROTO_VERSION"

# Every vendored copy, repo-relative. Keep this list in step with the expected
# set in tools/check-proto.sh — that script enumerates the working tree and
# fails on any plugin.proto it does not know about, so a stale list is loud.
COPIES=(
    "astra-plugin-sdk/proto/plugin.proto"
    "astra-plugin-sdk-python/astra_plugin_sdk/proto/plugin.proto"
)

die() {
    printf 'sync-proto: %s\n' "$1" >&2
    exit 1
}

# sha256sum(1) on Linux and git-bash, shasum(1) on macOS.
sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum -- "$1" | cut -d' ' -f1
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 -- "$1" | cut -d' ' -f1
    else
        die "need sha256sum or shasum on PATH"
    fi
}

canonical="$REPO_ROOT/$CANONICAL_REL"
[ -f "$canonical" ] || die "$CANONICAL_REL not found under $REPO_ROOT"

# The generator stamps `// protocol: N` into the header. That integer is the
# wire-protocol number every SDK reports in PluginRegisterRequest.
protocol="$(sed -n 's|^// protocol: *\([0-9][0-9]*\) *$|\1|p' "$canonical" | head -n1)"
[ -n "$protocol" ] || die "$CANONICAL_REL carries no \`// protocol: N\` header line"

sha="$(sha256_of "$canonical")"

for rel in "${COPIES[@]}"; do
    dest="$REPO_ROOT/$rel"
    mkdir -p -- "$(dirname -- "$dest")"
    cp -- "$canonical" "$dest"
    printf 'sync-proto: %s <- %s\n' "$rel" "$CANONICAL_REL"
done

cat >"$REPO_ROOT/$VERSION_REL" <<EOF
# The Astra plugin protocol, pinned.
#
# GENERATED by tools/sync-proto.sh from $CANONICAL_REL — DO NOT EDIT.
# Verified by tools/check-proto.sh.
#
#   protocol  The wire-protocol integer, copied from the \`// protocol: N\` header
#             the slicer stamps into $CANONICAL_REL. Every SDK's
#             PROTOCOL_VERSION and the release train check this value.
#
#   sha256    sha256 of $CANONICAL_REL, byte for byte. Every vendored
#             copy of the proto has this same hash; that is the invariant.
#             The TypeScript SDK independently records it as PROTO_SHA256 in
#             astra-plugin-sdk-ts/src/generated/index.ts.
#
protocol=$protocol
sha256=$sha
EOF
printf 'sync-proto: %s <- protocol=%s sha256=%s\n' "$VERSION_REL" "$protocol" "$sha"

printf 'sync-proto: %d cop%s in sync. Run tools/check-proto.sh to verify.\n' \
    "${#COPIES[@]}" "$([ "${#COPIES[@]}" -eq 1 ] && echo y || echo ies)"
