// SPDX-License-Identifier: GPL-3.0-or-later
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const args=process.argv.slice(2);
const value=flag=>args[args.indexOf(flag)+1];
const check=args.includes('--check');
const astra=args.includes('--astra-dir')?path.resolve(value('--astra-dir')):null;
const pkg=path.join(root,'astra-plugin-ui');
const vendor=path.join(root,'astra-plugin-cli/vendor/astra-plugin-ui');
function files(dir,prefix='') { return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(dir,e.name),prefix+e.name+'/'):[prefix+e.name]).sort(); }
const digest=b=>createHash('sha256').update(b).digest('hex');
if(astra) {
  for(const flag of ['--astra-ref','--plugins-ref']) if(!args.includes(flag)) throw new Error(flag+' is required for a cross-repository comparison');
  for(const [dir,ref] of [[astra,value('--astra-ref')],[root,value('--plugins-ref')]]) {
    if(ref!=='worktree') {
      let gitRoot=dir;
      while(!fs.existsSync(path.join(gitRoot,'.git'))) {
        const parent=path.dirname(gitRoot);
        if(parent===gitRoot) throw new Error('Not a Git checkout: '+dir);
        gitRoot=parent;
      }
      const git=a=>execFileSync('git',['-c','safe.directory='+gitRoot,...a],{cwd:dir,encoding:'utf8'}).trim();
      if(git(['rev-parse','HEAD'])!==git(['rev-parse',ref+'^{commit}'])) throw new Error('Checkout does not match explicit ref: '+ref);
      if(git(['status','--porcelain'])) throw new Error('Dirty checkout requires explicit ref worktree');
    }
  }
  execFileSync('bun',['run',check?'check:plugin-ui':'build:plugin-ui'],{cwd:path.join(astra,'astra-ui'),stdio:'inherit'});
  const generated=path.join(astra,'astra-ui/node_modules/.astra-plugin-ui/authoring');
  if (!check && fs.existsSync(pkg)) {
    const current=new Set(files(generated));
    for(const file of files(pkg)) if(!current.has(file)) fs.unlinkSync(path.join(pkg,file));
  }
  for(const file of files(generated)) {
    const bytes=fs.readFileSync(path.join(generated,file));
    if(check) { if(!fs.existsSync(path.join(pkg,file)) || !bytes.equals(fs.readFileSync(path.join(pkg,file)))) throw new Error('Astra snapshot drift: '+file); }
    else { fs.mkdirSync(path.dirname(path.join(pkg,file)),{recursive:true});fs.writeFileSync(path.join(pkg,file),bytes); }
  }
} else if(!check) throw new Error('Synchronization needs both checkouts and explicit refs');
const snapshot=JSON.parse(fs.readFileSync(path.join(pkg,'snapshot.json')));
const expected=Object.keys(snapshot).concat('snapshot.json').sort();
if(JSON.stringify(files(pkg))!==JSON.stringify(expected)) throw new Error('Unexpected or missing authoring files');
for(const [file,hash] of Object.entries(snapshot)) {
  const bytes=fs.readFileSync(path.join(pkg,file));
  if(digest(bytes)!==hash) throw new Error('Public snapshot integrity: '+file);
  if(file.endsWith(".d.ts") && ["components/ui", "src/", "../"].some(p=>bytes.toString().includes(p))) throw new Error("Private declaration path: "+file);
}
if (!check && fs.existsSync(vendor)) {
  const current=new Set(expected);
  for(const file of files(vendor)) if(!current.has(file)) fs.unlinkSync(path.join(vendor,file));
}
if (check && JSON.stringify(files(vendor))!==JSON.stringify(expected)) throw new Error('CLI vendor file set drift');
for(const file of expected) {
  const bytes=fs.readFileSync(path.join(pkg,file));
  if(check) { if(!fs.existsSync(path.join(vendor,file)) || !bytes.equals(fs.readFileSync(path.join(vendor,file)))) throw new Error('CLI vendor drift: '+file); }
  else {fs.mkdirSync(path.dirname(path.join(vendor,file)),{recursive:true});fs.writeFileSync(path.join(vendor,file),bytes);}
}
const rust="// Generated by tools/sync-ui-kit.mjs. SPDX-License-Identifier: GPL-3.0-or-later\npub const AUTHORING: &[(&str, &[u8])] = &[\n"+expected.map(f=>"("+JSON.stringify(f)+", include_bytes!("+JSON.stringify("../../vendor/astra-plugin-ui/"+f)+")),").join("\n")+"\n];\n";
const rustFile=path.join(root,'astra-plugin-cli/src/templates/ui_assets.rs');
if(check) {if(fs.readFileSync(rustFile,'utf8')!==rust) throw new Error('CLI resource table is stale');} else fs.writeFileSync(rustFile,rust);
console.log(astra?'UI Kit cross-repository comparison PASS (explicit refs)':'UI Kit public snapshot and CLI resources PASS (private correspondence not checked)');
