#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Minice — https://minice.ai
"""C33, run against template lists built to be wrong (registry plan AP-24).

    python3 tools/test_init_ci_templates.py        # the couplings job

The list has one template today, still written, compiling nothing, and no
release has stopped writing it. So every case C33 exists for is one the
committed tree has never held: a bumped constant, a stopping release, a period
that runs out, an audience a template compiles. Each test starts from a world
that is green, bends one thing, and asserts C33 goes red for that reason and no
other. The first test runs C33 on this tree as `rule_C33` gathers it. No network.
"""

from __future__ import annotations

import datetime
import importlib.util
import io
import unittest
from contextlib import redirect_stdout
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("crm", ROOT / "tools/check-registry-mirrors.py")
crm = importlib.util.module_from_spec(spec)
spec.loader.exec_module(crm)

AUDIENCE = "https://api.minice.ai/plugins/v1/author"
WAKE = "https://api.minice.ai/plugins/v1/author/wake"
TODAY = datetime.date(2027, 10, 1)
SHA_A, SHA_B = "a" * 40, "b" * 40
HEADER = crm.TEMPLATE_HEADER + "\n# Generated by `astra-plugin init-ci`.\njobs: {}\n"
RENDER = "pub fn render(…) { format!(r#\"…\"#, " + crm.TEMPLATE_ARG + ", …) }"


def world() -> dict:
    """Green: template 1 stopped at cli-v0.5.0, which writes template 2, and 2 is current."""
    docs = [
        {"version": "1", "emitted_by": ["cli-v0.2.1", "cli-v0.3.0", "cli-v0.4.0"],
         "author_audience": None, "notify_path": None,
         "stopped_by": "cli-v0.5.0", "stopped_on": "2026-09-28", "state": "live"},
        {"version": "2", "emitted_by": ["cli-v0.5.0", "cli-v0.6.0"],
         "author_audience": None, "notify_path": None,
         "stopped_by": None, "stopped_on": None, "state": "live"},
    ]
    tags = {
        "cli-v0.2.1": {"const": None, "render": True, "date": "2026-08-15"},
        "cli-v0.3.0": {"const": None, "render": True, "date": "2026-08-23"},
        "cli-v0.4.0": {"const": None, "render": True, "date": "2026-09-23"},
        "cli-v0.5.0": {"const": 2, "render": True, "date": "2026-09-27"},
    }
    token = {
        "templates": [{"version": d["version"], "audience": d["author_audience"],
                       "notify_path": d["notify_path"], "stopped_by": d["stopped_by"],
                       "state": d["state"]} for d in docs],
        "entries": [
            {"id": "audience:author", "kind": "audience", "value": AUDIENCE,
             "emitter": ["author-ci"], "state": "live"},
            {"id": "operation:author-ci:author.wake", "kind": "operation", "path": WAKE,
             "emitter": ["author-ci"], "state": "live"},
        ],
    }
    trust = {"signed": {"reusable_workflow_shas": [SHA_A, SHA_B]}}
    workflows = {SHA_A: "jobs:\n  plan: {}\n", SHA_B: "jobs:\n  plan: {}\n"}
    return {"docs": docs, "const": 2, "generated": HEADER, "render": RENDER, "tags": tags,
            "tree": "0.6.0", "today": TODAY, "token": token, "trust": trust, "workflows": workflows,
            "sources": {"templates": crm.TEMPLATES_SOURCE}, "pin": "c" * 40}


def run(w: dict, transcript: bool = False):
    """C33's failures on `w`; with `transcript`, also everything it printed,
    where each failure's detail lines are."""
    fails = crm.Fails()
    out = io.StringIO()
    with redirect_stdout(out):
        crm.c33_in_repo(fails, w["docs"], w["sources"], w["pin"], w["const"], w["generated"],
                        w["render"], w["tags"], w["tree"], w["today"])
        crm.c33_against_token(fails, w["docs"], w["token"], w["trust"],
                              lambda sha: w["workflows"][sha], "fixture", w["today"])
    return (list(fails), out.getvalue()) if transcript else list(fails)


class Tree(unittest.TestCase):
    def test_this_tree_is_green(self) -> None:
        fails = crm.Fails()
        out = io.StringIO()
        with redirect_stdout(out):
            crm.rule_C33(fails)
        self.assertEqual(list(fails), [], out.getvalue())
        self.assertIn("ok    C33 cli-v0.2.1's init-ci writes template 1", out.getvalue(),
                      "no release was read: the tags are missing, and the floor should have said so")

    def test_the_mirror_parses_and_refuses_what_it_cannot_read(self) -> None:
        docs, sources, pin = crm.read_templates_spec()
        self.assertEqual([d["version"] for d in docs], ["1"])
        self.assertEqual(sources.get("templates"), crm.TEMPLATES_SOURCE)
        self.assertRegex(pin or "", r"^[0-9a-f]{40}$")
        for bad in ("version: 1\n", "---\n- cli-v0.2.1\n", "---\nversion 1\n", "---\nstate: live\nstate: live\n"):
            with self.assertRaises(ValueError, msg=bad):
                crm.read_templates_spec(bad)


class World(unittest.TestCase):
    def assert_red(self, w: dict, *expect: str, n: int | None = None) -> None:
        """Red, saying each of `expect` (in a failure or its detail), and with
        exactly `n` failures (default: one per expectation), so a break that
        also trips something unrelated is not passed off as this one."""
        fails, out = run(w, transcript=True)
        self.assertTrue(fails, "the bent world is green")
        for e in expect:
            self.assertTrue(any(e in f for f in fails) or e in out, f"nothing says {e!r}: {fails}")
        want = len(expect) if n is None else n
        self.assertEqual(len(fails), want, f"{len(fails)} failed, this break explains {want}: {fails}")

    def test_the_green_world_is_green(self) -> None:
        self.assertEqual(run(world()), [])

    def test_a_bumped_constant_the_list_does_not_carry_is_red(self) -> None:
        w = world()
        w["const"] = 3
        self.assert_red(w, "CALLER_TEMPLATE_VERSION (3) is a listed template",
                        "cli-v0.6.0 (this tree, not tagged yet) writes template 2")

    def test_a_generated_file_without_the_header_is_red(self) -> None:
        w = world()
        w["generated"] = "# Generated by `astra-plugin init-ci`.\njobs: {}\n"
        self.assert_red(w, "first line is `# astra-plugin init-ci template {template}`")

    def test_a_template_that_calls_the_service_while_the_list_says_none_is_red(self) -> None:
        w = world()
        w["generated"] = HEADER + f"      audience: {AUDIENCE}\n"
        self.assert_red(w, "template 2 compiles no audience or path")

    def test_an_audience_retired_while_a_template_compiles_it_is_red(self) -> None:
        # ID-73's own case: the template list says template 2 compiles the
        # author audience, and the token file marks that audience retired.
        w = world()
        w["docs"][1]["author_audience"] = AUDIENCE
        w["generated"] = HEADER + f"      audience: {AUDIENCE}\n"
        w["token"]["templates"][1]["audience"] = AUDIENCE
        w["token"]["entries"][0]["state"] = "retired"
        self.assert_red(w, "ID-73: nothing a listed template or an allowlisted commit compiles is retired")

    def test_a_path_retired_while_an_allowlisted_commit_compiles_it_is_red(self) -> None:
        w = world()
        w["workflows"][SHA_B] += f"      run: curl -X POST {WAKE}\n"
        w["token"]["entries"][1]["state"] = "retired"
        self.assert_red(w, "ID-73")
        w["token"]["entries"][1]["state"] = "live"
        self.assertEqual(run(w), [], "a live path an allowlisted commit calls is what ID-73 permits")
        # The path starts with the audience. Calling the path alone is not
        # compiling the audience, so retiring the audience stays allowed here.
        w["token"]["entries"][0]["state"] = "retired"
        self.assertEqual(run(w), [], "the wake path was read as the audience it begins with")

    def test_retired_eleven_months_after_the_stop_is_red_in_both_places(self) -> None:
        w = world()
        w["today"] = datetime.date(2027, 8, 28)
        w["docs"][0]["state"] = "retired"
        w["token"]["templates"][0]["state"] = "retired"
        self.assert_red(w, "template 1 is not `retired` before 2027-09-28",
                        "the token file does not retire template 1 before its 12 months are up")
        w["today"] = datetime.date(2027, 9, 28)
        self.assertEqual(run(w), [], "on the day the 12 months end, retiring is allowed")

    def test_retired_thirteen_months_back_in_the_list_while_the_token_file_says_live_is_red(self) -> None:
        w = world()
        w["docs"][0]["stopped_on"] = "2026-09-28"
        w["today"] = datetime.date(2027, 10, 28)
        w["docs"][0]["state"] = "retired"
        self.assert_red(w, "member by member", "template 1 state: we say 'retired', the token file's `state` says 'live'", n=1)

    def test_a_stopping_release_that_does_not_exist_is_red(self) -> None:
        w = world()
        w["docs"][0]["stopped_by"] = "cli-v0.4.9"
        w["token"]["templates"][0]["stopped_by"] = "cli-v0.4.9"
        self.assert_red(w, "template 1's stopping release cli-v0.4.9 is this tree's, untagged")

    def test_a_stop_day_before_the_release_commit_is_red(self) -> None:
        w = world()
        w["docs"][0]["stopped_on"] = "2026-09-20"
        self.assert_red(w, "stop day '2026-09-20' is a date no earlier than cli-v0.5.0's commit")

    def test_a_stopping_release_that_still_writes_the_template_is_red(self) -> None:
        w = world()
        w["tags"]["cli-v0.5.0"]["const"] = 1
        self.assert_red(w, "cli-v0.5.0 really stopped writing template 1",
                        "cli-v0.5.0's init-ci writes template 2")

    def test_an_unlisted_release_and_a_listed_release_that_does_not_exist_are_red(self) -> None:
        w = world()
        w["tags"]["cli-v0.5.1"] = {"const": 2, "render": True, "date": "2026-10-02"}
        self.assert_red(w, "cli-v0.5.1 is listed under exactly one template ([])")
        w = world()
        w["docs"][1]["emitted_by"].append("cli-v0.5.7")
        self.assert_red(w, "cli-v0.5.7, listed under template ['2'], is a release")

    def test_this_trees_own_release_must_be_listed_before_it_is_tagged(self) -> None:
        w = world()
        w["docs"][1]["emitted_by"].remove("cli-v0.6.0")
        self.assert_red(w, "this tree's release, cli-v0.6.0, is listed")

    def test_the_mirror_and_the_token_file_differ_member_by_member(self) -> None:
        w = world()
        w["token"]["templates"][1]["notify_path"] = WAKE
        self.assert_red(w, "member by member", "template 2 notify_path: we say None", n=1)
        w = world()
        del w["token"]["templates"][0]
        self.assert_red(w, "member by member", "versions: we list ['1', '2'], the token file ['2']", n=1)

    def test_the_floors(self) -> None:
        w = world()
        w["trust"]["signed"]["reusable_workflow_shas"] = []
        self.assert_red(w, "floor: trust.json allows 0 reusable-workflow commit(s)")
        w = world()
        w["token"]["entries"] = [w["token"]["entries"][1]]
        self.assert_red(w, "floor: the token file records the author audience and the author-notify path")
        w = world()
        w["tags"] = {t: i for t, i in w["tags"].items() if t == "cli-v0.5.0"}
        fails = run(w)
        self.assertTrue(any("floor: 1 `cli-v` tag(s) read" in f for f in fails), fails)

    def test_twelve_months_from_a_leap_day(self) -> None:
        self.assertEqual(crm._support_ends(datetime.date(2028, 2, 29)), datetime.date(2029, 2, 28))
        self.assertEqual(crm._support_ends(datetime.date(2026, 9, 28)), datetime.date(2027, 9, 28))


if __name__ == "__main__":
    unittest.main(verbosity=2)
