#!/usr/bin/env python3
"""Render every generated artefact of `spec/hooks.yaml`.

    python3 tools/parity/gen.py            # write the files
    python3 tools/parity/gen.py --check    # fail if the checked-in copies differ

Outputs (all carry a DO NOT EDIT banner):
    docs/en/parity.md                  the cross-language drift dashboard
    docs/en/hooks/rust.md              per-SDK hook table
    docs/en/hooks/python.md
    docs/en/hooks/typescript.md
    spec/generated/conformance.json    the hook list a conformance run must cover

Generation reads ONLY the spec, never the SDK sources, so the output is a pure
function of a checked-in file and `--check` is a meaningful gate. Comparing the
spec against the sources is `tools/parity/check.py`'s job.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import spec  # noqa: E402  (sys.path is set above)

REPO_ROOT = spec.REPO_ROOT
BANNER_MD = (
    "<!-- GENERATED by tools/parity/gen.py from spec/hooks.yaml — DO NOT EDIT.\n"
    "     Change the hook in spec/hooks.yaml and re-run the generator. -->\n"
)

STATUS_MARK = {"stable": "stable", "planned": "planned", "n/a": "n/a"}


def _status_cell(hook: dict, lang: str) -> str:
    status = hook[lang]
    if status == "planned":
        return f"planned → {hook[f'{lang}_grace_until']}"
    return STATUS_MARK[status]


def _provenance(doc: dict, hook: dict) -> str:
    if hook["daemon_calls"] == "none":
        return "**none**"
    return f"`{doc['astra_daemon_root']}/{hook['daemon_calls']}`"


def _by_service(doc: dict, service: str) -> list[dict]:
    return [h for h in doc["hooks"] if h["service"] == service]


def _capability_order(doc: dict) -> list[str]:
    order: list[str] = []
    for hook in doc["hooks"]:
        if hook["capability"] not in order:
            order.append(hook["capability"])
    return order


# ── findings ─────────────────────────────────────────────────────────────────

def _findings(doc: dict) -> list[str]:
    """Everything the spec says is wrong with the world, derived, not written."""
    out: list[str] = []

    unrouted = [h for h in doc["hooks"] if h["routing"] == "unrouted"]
    for hook in unrouted:
        bound = [spec.LANGUAGE_LABELS[l] for l in spec.LANGUAGES if hook[l] == "stable"]
        tail = f" — bound anyway in {', '.join(bound)}" if bound else ""
        out.append(
            f"**`{hook['rpc']}` is unrouted.** The proto declares it and no daemon call "
            f"site exists{tail}. Either wire it or retire it; today it is a promise the "
            f"daemon does not keep."
        )

    for hook in [h for h in doc["hooks"] if h["routing"] == "deprecated"]:
        bound = [spec.LANGUAGE_LABELS[l] for l in spec.LANGUAGES if hook[l] == "stable"]
        out.append(
            f"**`{hook['rpc']}` is deprecated but still bound** in {', '.join(bound) or 'no SDK'}. "
            f"Keep the bindings so an old plugin keeps getting `UNIMPLEMENTED` rather than a "
            f"transport error; add no new ones."
        )

    for hook in doc["hooks"]:
        if hook["requirement"] != "required" or hook["routing"] != "live":
            continue
        gaps = [spec.LANGUAGE_LABELS[l] for l in spec.LANGUAGES if hook[l] != "stable"]
        if not gaps:
            continue
        if len(gaps) == len(spec.LANGUAGES):
            out.append(
                f"**`{hook['capability']}` is a capability nobody can implement.** "
                f"`{hook['rpc']}` is required for it and no SDK binds it."
            )
        else:
            out.append(
                f"**`{hook['capability']}` is not available in {', '.join(gaps)}.** "
                f"`{hook['rpc']}` is required for it and only "
                f"{', '.join(spec.LANGUAGE_LABELS[l] for l in spec.LANGUAGES if hook[l] == 'stable')} "
                f"binds it."
            )

    for hook in doc["hooks"]:
        if hook["requirement"] != "optional" or hook["routing"] != "live":
            continue
        stable = [l for l in spec.LANGUAGES if hook[l] == "stable"]
        if stable and len(stable) < len(spec.LANGUAGES):
            missing = [spec.LANGUAGE_LABELS[l] for l in spec.LANGUAGES if hook[l] != "stable"]
            out.append(
                f"**`{hook['rpc']}` is uneven.** Bound in "
                f"{', '.join(spec.LANGUAGE_LABELS[l] for l in stable)}, missing in "
                f"{', '.join(missing)} — the exact shape of drift this file exists to catch."
            )
    return out


# ── parity.md ────────────────────────────────────────────────────────────────

def render_parity(doc: dict) -> str:
    lines: list[str] = [BANNER_MD, "# Hook parity", ""]
    hooks = doc["hooks"]
    lines += [
        f"Protocol **{doc['protocol']}** · **{len(hooks)}** hooks · source of truth "
        f"[`spec/hooks.yaml`](../../spec/hooks.yaml).",
        "",
        "A *hook* is one RPC on one of the two plugin-facing services. "
        "`PluginCapabilityService` runs **daemon → plugin**: your plugin serves it and the "
        "daemon calls in. `PluginHostService` runs **plugin → daemon**: the daemon serves it "
        "and your plugin calls out. `PluginService` is not here — the daemon serves it to the "
        "Astra UI and no plugin ever touches it.",
        "",
        "| Column | Meaning |",
        "|---|---|",
        "| **Capability** | The `[capabilities]` key in `plugin.toml` this hook belongs to, or `core` for hooks every plugin has. |",
        "| **Permission** | `PluginHostService` only. The `[permissions]` key the daemon gates the call on (§5.6), or `none` if every plugin may always call it. **Not the same question as Capability:** the capability says which feature the call is part of, the permission is what the user consented to, and the daemon answers out of the *granted* permission set. Verified against the daemon's `HOST_RPC_PERMISSIONS` by rule R6. |",
        "| **Req** | `required` — the capability does not work without the hook. `optional` — the daemon carries on when it is absent. |",
        "| **Routing** | `live` — the daemon really calls it, and the call site is named. `unrouted` — declared in the proto, called by nobody. `deprecated` — being retired. |",
        "| `stable` | The SDK binds this rpc to a handler that does work — verified against its source by `tools/parity/check.py` rule R1, which resolves the dispatch target (TypeScript's `.bind(this)`, Python's servicer method, Rust's `async fn`) and reads *that* body. Whether the binding reaches anything when a real plugin process is driven through it is rule R7's question, not R1's. |",
        "| `planned` | Committed, not shipped. The date is the grace deadline; rule R4 fails the build once it passes. |",
        "| `n/a` | Not implemented and not committed. A registered handler whose body only answers `UNIMPLEMENTED` counts as `n/a`, because on the wire that *is* an absent hook — R1 reads the handler body for exactly this. |",
        "",
    ]

    findings = _findings(doc)
    lines += ["## Findings", ""]
    if findings:
        lines.append(
            "Derived from the rows below, not written by hand. Each one is a way a plugin "
            "author's code fails today."
        )
        lines.append("")
        lines += [f"{i}. {text}" for i, text in enumerate(findings, start=1)]
    else:
        lines.append("None. Every live hook is bound in every SDK.")
    lines.append("")

    for service in spec.SERVICES:
        rows = _by_service(doc, service)
        host = service == "PluginHostService"
        perm_head = " Permission |" if host else ""
        perm_rule = "---|" if host else ""
        lines += [
            f"## {service} — {spec.DIRECTIONS[service].replace('->', ' → ')}",
            "",
            f"| RPC | Capability |{perm_head} Req | Routing | Stream | Rust | Python | TypeScript | Daemon call site |",
            f"|---|---|{perm_rule}---|---|---|---|---|---|---|",
        ]
        for hook in rows:
            lines.append(
                ("| `{rpc}` | `{cap}` |" + (" `{perm}` |" if host else "") +
                 " {req} | {routing} | {stream} | {rs} | {py} | {ts} | {prov} |").format(
                    rpc=hook["rpc"],
                    cap=hook["capability"],
                    perm=hook.get("permission", ""),
                    req=hook["requirement"],
                    routing=hook["routing"],
                    stream=hook["streaming"],
                    rs=_status_cell(hook, "rust"),
                    py=_status_cell(hook, "python"),
                    ts=_status_cell(hook, "typescript"),
                    prov=_provenance(doc, hook),
                )
            )
        lines.append("")

    lines += ["## Capability readiness", "", "Can a plugin written in this language implement this capability at all today?", "", "| Capability | Rust | Python | TypeScript |", "|---|---|---|---|"]
    for capability in _capability_order(doc):
        cells = []
        for lang in spec.LANGUAGES:
            blockers = [
                h["rpc"] for h in doc["hooks"]
                if h["capability"] == capability
                and h["requirement"] == "required"
                and h["routing"] == "live"
                and h[lang] != "stable"
            ]
            cells.append("yes" if not blockers else "no — needs " + ", ".join(f"`{b}`" for b in blockers))
        lines.append(f"| `{capability}` | {cells[0]} | {cells[1]} | {cells[2]} |")
    lines.append("")

    conformance = _conformance_hooks(doc)
    lines += [
        "## Conformance coverage",
        "",
        f"The {len(conformance)} inbound hooks a conformance run must exercise — every "
        "`daemon → plugin` hook the daemon actually calls. `astra-plugin test` calls each one "
        "implied by the plugin's declared capabilities and asserts no `UNIMPLEMENTED` for the "
        "`required` ones; `optional` hooks are exempt, because `Unimplemented → hook absent` "
        "is the forward-compat contract and a scaffold declaring everything would otherwise be "
        "indistinguishable from a broken plugin. Machine-readable copy: "
        "[`spec/generated/conformance.json`](../../spec/generated/conformance.json).",
        "",
        "| RPC | Capability | Req | Stream | Phase |",
        "|---|---|---|---|---|",
    ]
    for hook in conformance:
        lines.append(
            f"| `{hook['rpc']}` | `{hook['capability']}` | {hook['requirement']} | "
            f"{hook['streaming']} | {_phase(hook)} |"
        )
    lines.append("")

    noted = [h for h in doc["hooks"] if h.get("note")]
    if noted:
        lines += ["## Notes", ""]
        for hook in noted:
            lines.append(f"- **`{hook['rpc']}`** — {hook['summary']} {hook['note']}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ── per-SDK tables ───────────────────────────────────────────────────────────

def render_sdk(doc: dict, lang: str) -> str:
    label = spec.LANGUAGE_LABELS[lang]
    lines = [BANNER_MD, f"# {label} SDK — hook table", ""]
    lines += [
        f"Protocol **{doc['protocol']}**. Every hook the {label} SDK can bind, and whether it "
        f"does. Generated from [`spec/hooks.yaml`](../../../spec/hooks.yaml); the cross-language "
        f"view is [`parity.md`](../parity.md).",
        "",
    ]

    for service in spec.SERVICES:
        rows = _by_service(doc, service)
        verb = "You implement these; the daemon calls them." if service == "PluginCapabilityService" \
            else "The daemon implements these; you call them."
        host = service == "PluginHostService"
        lines += [
            f"## {service} — {spec.DIRECTIONS[service].replace('->', ' → ')}",
            "",
            verb,
            "",
        ]
        if host:
            lines += [
                "**Capability is not enough here.** These are calls you make into the daemon, "
                "and the daemon answers them out of the *granted* permission set (§5.6). "
                "Declaring the capability says which feature the call belongs to; declaring "
                "the permission is what the user consents to. A plugin that declares only the "
                "capability gets `permission_denied` on the user's machine. `none` means every "
                "plugin may always call it.",
                "",
                "| RPC | Capability | Permission | Req | Stream | Status | What it does |",
                "|---|---|---|---|---|---|---|",
            ]
        else:
            lines += [
                "| RPC | Capability | Req | Stream | Status | What it does |",
                "|---|---|---|---|---|---|",
            ]
        for hook in rows:
            perm = f" `{hook['permission']}` |" if host else ""
            lines.append(
                f"| `{hook['rpc']}` | `{hook['capability']}` |{perm} {hook['requirement']} | "
                f"{hook['streaming']} | {_status_cell(hook, lang)} | {hook['summary']} |"
            )
        lines.append("")

    planned = [h for h in doc["hooks"] if h[lang] == "planned"]
    absent = [h for h in doc["hooks"] if h[lang] == "n/a"]
    lines += ["## Gaps", ""]
    if not planned and not absent:
        lines += [f"None. The {label} SDK binds every hook in the spec.", ""]
    if planned:
        lines += ["Committed, not shipped. The date is the deadline after which CI fails:", ""]
        for hook in planned:
            lines.append(
                f"- `{hook['rpc']}` — by **{hook[f'{lang}_grace_until']}** "
                f"(tracked in `{hook[f'{lang}_issue']}`). {hook['summary']}"
            )
        lines.append("")
    if absent:
        lines += ["Deliberately unbound:", ""]
        for hook in absent:
            lines.append(f"- `{hook['rpc']}` — {hook[f'{lang}_reason']}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ── conformance list ─────────────────────────────────────────────────────────

def _phase(hook: dict) -> str:
    return "teardown" if hook["rpc"] == "Shutdown" else "probe"


def _conformance_hooks(doc: dict) -> list[dict]:
    inbound = [
        h for h in doc["hooks"]
        if h["direction"] == "daemon->plugin" and h["routing"] == "live"
    ]
    # Shutdown kills the process it is sent to, so it can only be last.
    return sorted(inbound, key=lambda h: (_phase(h) == "teardown",))


def render_conformance(doc: dict) -> str:
    payload = {
        "$generated_by": "tools/parity/gen.py from spec/hooks.yaml — DO NOT EDIT",
        "protocol": doc["protocol"],
        "contract": (
            "Call each hook implied by the plugin's declared capabilities, in order. "
            "requirement=required must not answer UNIMPLEMENTED; requirement=optional may. "
            "phase=teardown runs last: Shutdown ends the process it is sent to."
        ),
        "hooks": [
            {
                "rpc": h["rpc"],
                "capability": h["capability"],
                "requirement": h["requirement"],
                "streaming": h["streaming"],
                "phase": _phase(h),
            }
            for h in _conformance_hooks(doc)
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


# ── driver ───────────────────────────────────────────────────────────────────

def artefacts(doc: dict) -> dict[Path, str]:
    out = {
        REPO_ROOT / "docs" / "en" / "parity.md": render_parity(doc),
        REPO_ROOT / "spec" / "generated" / "conformance.json": render_conformance(doc),
    }
    for lang in spec.LANGUAGES:
        out[REPO_ROOT / "docs" / "en" / "hooks" / f"{lang}.md"] = render_sdk(doc, lang)
    return out


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    args = parser.parse_args(argv)

    try:
        doc = spec.load()
    except spec.SpecError as exc:
        print(f"spec/hooks.yaml is malformed:\n  {exc}", file=sys.stderr)
        return 2

    stale = 0
    for path, content in artefacts(doc).items():
        rel = path.relative_to(REPO_ROOT)
        if args.check:
            on_disk = path.read_text(encoding="utf-8") if path.exists() else ""
            if on_disk != content:
                stale += 1
                print(f"STALE  {rel}", file=sys.stderr)
                diff = difflib.unified_diff(
                    on_disk.splitlines(True), content.splitlines(True),
                    fromfile=f"{rel} (checked in)", tofile=f"{rel} (generated)",
                )
                sys.stderr.writelines(diff)
            else:
                print(f"ok     {rel}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote  {rel}")

    if stale:
        print(
            f"\n{stale} generated file(s) do not match spec/hooks.yaml. "
            f"Run `python3 tools/parity/gen.py` and commit the result.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
